import type { Exercise } from './types'

/** Übungen für den siebten bis zwölften Monat (Woche 26 bis 52). */
export const CRAWLER_EXERCISES: Exercise[] = [
  {
    id: 'cr-tunnel',
    title: 'Durch den Tunnel',
    fromWeeks: 30,
    toWeeks: 104,
    area: 'motorik',
    goal: 'Krabbeln mit einem Ziel verbinden.',
    material: 'Ein großer Karton oder ein Stoffspieltunnel',
    steps: [
      'Öffnet den Karton an beiden Enden.',
      'Setzt euch an das andere Ende und ruft euer Kind.',
      'Lasst am Anfang die Seiten offen, falls es unheimlich wirkt.',
      'Legt später ein Spielzeug in die Mitte.',
    ],
    durationMin: 10,
  },
  {
    id: 'cr-einraeumen',
    title: 'Ein- und Ausräumen',
    fromWeeks: 30,
    toWeeks: 104,
    area: 'kognition',
    goal: 'Behälter und Inhalt verstehen, Feinmotorik üben.',
    material: 'Eine Schüssel und mehrere große Gegenstände',
    steps: [
      'Stellt die Schüssel gefüllt vor euer Kind.',
      'Zeigt einmal das Herausnehmen und Hineinlegen.',
      'Lasst es selbst machen, so lange es will.',
      'Benennt die Gegenstände beim Herausnehmen.',
    ],
    durationMin: 12,
  },
  {
    id: 'cr-hochziehen',
    title: 'An der Couch hochziehen',
    fromWeeks: 30,
    toWeeks: 52,
    area: 'motorik',
    goal: 'Kraft und Gleichgewicht für den Stand aufbauen.',
    material: 'Ein stabiles niedriges Möbelstück',
    steps: [
      'Legt ein Spielzeug auf die Sitzfläche.',
      'Setzt euer Kind davor auf den Boden.',
      'Lasst es sich selbst hochziehen, helft nur bei Bedarf.',
      'Übt danach das Hinsetzen: Knie beugen, Po nach hinten.',
    ],
    durationMin: 10,
  },
  {
    id: 'cr-hinsetzen-ueben',
    title: 'Vom Stand zum Sitzen',
    fromWeeks: 32,
    toWeeks: 56,
    area: 'motorik',
    goal: 'Den Weg nach unten lernen – das erspart nächtliches Steckenbleiben.',
    material: 'Ein niedriges Möbel',
    steps: [
      'Wenn euer Kind steht, führt seine Hände nach unten.',
      'Beugt sanft die Knie, sodass es auf den Po plumpst.',
      'Macht daraus ein Spiel mit einem festen Wort, etwa "plumps".',
      'Wiederholt es mehrmals täglich, bis es allein klappt.',
    ],
    durationMin: 6,
  },
  {
    id: 'cr-pinzette-cheerios',
    title: 'Kleine Stücke aufheben',
    fromWeeks: 34,
    toWeeks: 78,
    area: 'motorik',
    goal: 'Den Pinzettengriff mit Daumen und Zeigefinger üben.',
    material: 'Weiche Getreideringe ohne Zucker',
    steps: [
      'Legt fünf Stück auf den Tisch vor euer Kind.',
      'Zeigt einmal, wie ihr eines mit zwei Fingern aufhebt.',
      'Lasst euer Kind probieren, auch wenn es zuerst die ganze Hand nimmt.',
      'Bleibt daneben sitzen.',
    ],
    durationMin: 8,
  },
  {
    id: 'cr-winken',
    title: 'Winken lernen',
    fromWeeks: 32,
    toWeeks: 60,
    area: 'sozial',
    goal: 'Eine erste soziale Geste aufbauen.',
    material: 'Nichts',
    steps: [
      'Winkt bei jedem Abschied deutlich und sagt "Tschüss".',
      'Führt anfangs die Hand eures Kindes.',
      'Wartet danach ab, ohne zu drängen.',
      'Freut euch sichtbar, wenn es zum ersten Mal selbst winkt.',
    ],
    durationMin: 2,
  },
  {
    id: 'cr-zeigen-benennen',
    title: 'Zeigen und benennen',
    fromWeeks: 34,
    toWeeks: 104,
    area: 'sprache',
    goal: 'Geteilte Aufmerksamkeit – die wichtigste Vorstufe zur Sprache.',
    material: 'Ein Bilderbuch oder das Fenster',
    steps: [
      'Wartet, bis euer Kind auf etwas zeigt.',
      'Schaut hin und benennt es klar: "Ja, ein Hund."',
      'Fügt einen kurzen Satz hinzu.',
      'Zeigt auch selbst auf Dinge und benennt sie.',
    ],
    durationMin: 6,
  },
  {
    id: 'cr-stapelturm',
    title: 'Turm bauen und umwerfen',
    fromWeeks: 36,
    toWeeks: 104,
    area: 'kognition',
    goal: 'Ursache und Wirkung erleben, Feinmotorik üben.',
    material: 'Vier große Bausteine',
    steps: [
      'Baut einen Turm aus zwei Steinen.',
      'Lasst euer Kind ihn umwerfen – das ist der beliebteste Teil.',
      'Baut wieder auf und ladet zum Mitbauen ein.',
      'Zählt die Steine laut mit.',
    ],
    durationMin: 10,
  },
  {
    id: 'cr-versteckspiel-decke',
    title: 'Spielzeug unter der Decke',
    fromWeeks: 30,
    toWeeks: 78,
    area: 'kognition',
    goal: 'Objektpermanenz festigen.',
    material: 'Ein Tuch und ein Spielzeug',
    steps: [
      'Zeigt eurem Kind das Spielzeug.',
      'Legt es sichtbar unter das Tuch.',
      'Fragt: "Wo ist es?" und wartet.',
      'Zeigt es freudig, wenn euer Kind es findet.',
    ],
    durationMin: 6,
  },
  {
    id: 'cr-treppe-rueckwaerts',
    title: 'Rückwärts von der Stufe',
    fromWeeks: 38,
    toWeeks: 104,
    area: 'motorik',
    goal: 'Sicher von erhöhten Flächen herunterkommen.',
    material: 'Eine niedrige Stufe oder Matratze',
    steps: [
      'Dreht euer Kind auf dem Bauch mit den Füßen voran.',
      'Führt die Beine über die Kante.',
      'Sagt jedes Mal dasselbe Wort, etwa "Füßchen zuerst".',
      'Übt es täglich, bis es von allein kommt.',
    ],
    durationMin: 6,
  },
  {
    id: 'cr-becher-trinken',
    title: 'Aus dem Becher trinken',
    fromWeeks: 30,
    toWeeks: 78,
    area: 'alltag',
    goal: 'Vom Saugen zum Trinken übergehen.',
    material: 'Ein kleiner offener Becher',
    steps: [
      'Füllt einen Fingerbreit Wasser ein.',
      'Führt den Becher an die Lippen und kippt minimal.',
      'Lasst euer Kind selbst halten, sobald es will.',
      'Rechnet mit nassen Kleidern – das gehört dazu.',
    ],
    durationMin: 8,
  },
  {
    id: 'cr-klatschen',
    title: 'Klatschen im Takt',
    fromWeeks: 32,
    toWeeks: 104,
    area: 'sozial',
    goal: 'Nachahmung und Rhythmusgefühl.',
    material: 'Nichts',
    steps: [
      'Klatscht langsam und deutlich.',
      'Nehmt die Hände eures Kindes und klatscht damit.',
      'Macht eine Pause und schaut, ob es weiterklatscht.',
      'Verbindet es mit einem Lied.',
    ],
    durationMin: 5,
  },
  {
    id: 'cr-buchstaben-nein',
    title: 'Ein klares Nein',
    fromWeeks: 34,
    toWeeks: 104,
    area: 'sozial',
    goal: 'Grenzen verständlich machen, ohne zu schimpfen.',
    material: 'Nichts',
    steps: [
      'Sagt bei Gefahr ein kurzes, deutliches Nein.',
      'Nehmt euer Kind aus der Situation heraus.',
      'Bietet sofort eine erlaubte Alternative an.',
      'Verwendet Nein sparsam, sonst verliert es die Wirkung.',
    ],
    durationMin: 1,
  },
  {
    id: 'cr-fingerfarben',
    title: 'Malen mit Joghurt',
    fromWeeks: 34,
    toWeeks: 104,
    area: 'sinne',
    goal: 'Materialerfahrung ohne Sorge, dass etwas im Mund landet.',
    material: 'Naturjoghurt, etwas Fruchtmus zum Färben, ein Tablett',
    steps: [
      'Gebt einen Klecks Joghurt auf ein Tablett.',
      'Zeigt einmal, wie man darin Spuren zieht.',
      'Lasst euer Kind mit den Fingern malen.',
      'Zieht es vorher aus, das erspart die Wäsche.',
    ],
    durationMin: 12,
  },
  {
    id: 'cr-abwechselnd-geben',
    title: 'Geben und Nehmen',
    fromWeeks: 32,
    toWeeks: 78,
    area: 'sozial',
    goal: 'Gegenseitigkeit erleben.',
    material: 'Ein kleines Spielzeug',
    steps: [
      'Gebt eurem Kind das Spielzeug und sagt "für dich".',
      'Haltet die Hand auf und sagt "für mich".',
      'Bedankt euch übertrieben, wenn es zurückkommt.',
      'Wiederholt es, solange es Spaß macht.',
    ],
    durationMin: 6,
  },
  {
    id: 'cr-hindernisparcours',
    title: 'Kleiner Parcours',
    fromWeeks: 36,
    toWeeks: 104,
    area: 'motorik',
    goal: 'Verschiedene Bewegungsmuster kombinieren.',
    material: 'Kissen, Decke, ein Karton',
    steps: [
      'Baut eine kurze Strecke mit drei Hindernissen.',
      'Krabbelt einmal selbst vor.',
      'Lockt euer Kind mit einem Ziel am Ende.',
      'Ändert die Strecke nach ein paar Tagen.',
    ],
    durationMin: 12,
  },
  {
    id: 'cr-tierlaute',
    title: 'Tierlaute',
    fromWeeks: 36,
    toWeeks: 104,
    area: 'sprache',
    goal: 'Erste Wörter über Lautmalerei anbahnen.',
    material: 'Ein Tierbuch oder Tierfiguren',
    steps: [
      'Zeigt ein Tier und macht den passenden Laut.',
      'Wiederholt ihn zwei- bis dreimal.',
      'Macht eine Pause und schaut, ob euer Kind einsteigt.',
      'Bleibt bei wenigen Tieren, statt viele durchzugehen.',
    ],
    durationMin: 8,
  },
  {
    id: 'cr-schuhe-anziehen',
    title: 'Beim Anziehen mithelfen',
    fromWeeks: 40,
    toWeeks: 104,
    area: 'alltag',
    goal: 'Kooperation im Alltag aufbauen.',
    material: 'Kleidung',
    steps: [
      'Kündigt an: "Jetzt kommt der Arm in den Ärmel."',
      'Wartet einen Moment, ob euer Kind den Arm hebt.',
      'Bedankt euch für die Hilfe.',
      'Plant dafür ein paar Minuten mehr ein.',
    ],
    durationMin: 5,
  },
  {
    id: 'cr-schieben',
    title: 'Etwas schieben',
    fromWeeks: 40,
    toWeeks: 78,
    area: 'motorik',
    goal: 'Das Stehen und erste Schritte mit Halt üben.',
    material: 'Ein stabiler Karton mit etwas Gewicht darin',
    steps: [
      'Stellt den Karton vor euer stehendes Kind.',
      'Zeigt, dass er beim Schieben nachgibt.',
      'Beschwert ihn, wenn er zu leicht wegrutscht.',
      'Bleibt daneben – gestoppt wird noch nicht kontrolliert.',
    ],
    durationMin: 10,
  },
  {
    id: 'cr-loch-stecken',
    title: 'Durchs Loch stecken',
    fromWeeks: 38,
    toWeeks: 104,
    area: 'kognition',
    goal: 'Form und Größe abschätzen lernen.',
    material: 'Eine Dose mit rundem Deckelloch, große Holzscheiben',
    steps: [
      'Schneidet ein Loch in einen Plastikdeckel.',
      'Zeigt einmal, wie eine Scheibe hineinfällt.',
      'Gebt eurem Kind die Scheiben.',
      'Helft, indem ihr die Dose ruhig haltet.',
    ],
    durationMin: 10,
  },
  {
    id: 'cr-hoehe-erlauben',
    title: 'Sicheres Klettern anbieten',
    fromWeeks: 42,
    toWeeks: 104,
    area: 'motorik',
    goal: 'Den Kletterdrang in einer sicheren Umgebung ausleben.',
    material: 'Zwei Matratzen oder ein niedriges Podest',
    steps: [
      'Legt eine Matratze auf den Boden, eine halb darüber.',
      'Zeigt den Auf- und Abstieg.',
      'Bleibt in Griffweite, ohne einzugreifen.',
      'Erhöht die Schwierigkeit langsam.',
    ],
    durationMin: 12,
  },
  {
    id: 'cr-morgenlied',
    title: 'Immer derselbe Ablauf',
    fromWeeks: 30,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Sicherheit durch Vorhersehbarkeit.',
    material: 'Nichts',
    steps: [
      'Legt eine feste Reihenfolge für den Morgen fest.',
      'Begleitet jeden Schritt mit demselben Satz oder Lied.',
      'Haltet die Reihenfolge auch an schlechten Tagen ein.',
      'Ändert sie nur bewusst, nicht zufällig.',
    ],
    durationMin: 1,
  },
  {
    id: 'cr-sortieren-gross-klein',
    title: 'Groß und klein',
    fromWeeks: 44,
    toWeeks: 104,
    area: 'kognition',
    goal: 'Erste Größenvergleiche anstellen.',
    material: 'Zwei Schüsseln, große und kleine Gegenstände',
    steps: [
      'Legt einen großen und einen kleinen Gegenstand nebeneinander.',
      'Benennt: "Das ist groß, das ist klein."',
      'Gebt eurem Kind die Gegenstände zum Vergleichen.',
      'Erwartet noch kein richtiges Sortieren.',
    ],
    durationMin: 8,
  },
  {
    id: 'cr-buch-eigenes',
    title: 'Ein Buch nur fürs Kind',
    fromWeeks: 32,
    toWeeks: 104,
    area: 'sprache',
    goal: 'Bücher als etwas Eigenes erleben, auch wenn sie leiden.',
    material: 'Ein robustes Pappbuch',
    steps: [
      'Gebt eurem Kind ein Buch, das es allein benutzen darf.',
      'Lasst zu, dass es daran zieht und darauf beißt.',
      'Legt es an einen erreichbaren Platz.',
      'Bewahrt empfindlichere Bücher woanders auf.',
    ],
    durationMin: 8,
  },
  {
    id: 'cr-schnur-ziehen',
    title: 'An der Schnur ziehen',
    fromWeeks: 36,
    toWeeks: 78,
    area: 'kognition',
    goal: 'Verstehen, dass ein Zug an der Schnur den Gegenstand bewegt.',
    material: 'Ein Spielzeug mit einer kurzen, dicken Schnur',
    steps: [
      'Legt das Spielzeug außer Reichweite, die Schnur erreichbar.',
      'Zieht einmal vor.',
      'Wartet, ob euer Kind die Verbindung erkennt.',
      'Nur unter Aufsicht, Schnüre gehören danach weg.',
    ],
    durationMin: 8,
  },
  {
    id: 'cr-wasser-umgiessen',
    title: 'Umgießen',
    fromWeeks: 44,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Feinmotorik, Konzentration und Ursache-Wirkung in einem.',
    material: 'Zwei kleine Becher, etwas Wasser, ein Tablett',
    steps: [
      'Stellt beide Becher auf ein Tablett.',
      'Gießt einmal langsam von einem in den anderen.',
      'Lasst euer Kind es probieren.',
      'Ein Tuch bereitlegen und nicht kommentieren, was danebengeht.',
    ],
    durationMin: 10,
  },
  {
    id: 'cr-gemeinsam-aufraeumen',
    title: 'Gemeinsam wegräumen',
    fromWeeks: 44,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Aufräumen als selbstverständlichen Teil des Spiels etablieren.',
    material: 'Eine Kiste',
    steps: [
      'Kündigt das Ende des Spiels an.',
      'Singt dabei immer dasselbe kurze Lied.',
      'Räumt gemeinsam, nicht als Aufgabe für das Kind.',
      'Lobt das Mitmachen, nicht das Ergebnis.',
    ],
    durationMin: 5,
  },
  {
    id: 'cr-erste-schritte-haende',
    title: 'An zwei Händen gehen',
    fromWeeks: 42,
    toWeeks: 60,
    area: 'motorik',
    goal: 'Das Gehen mit Unterstützung üben, ohne die Schultern zu belasten.',
    material: 'Nichts',
    steps: [
      'Haltet euer Kind an beiden Händen auf Schulterhöhe, nicht darüber.',
      'Geht langsam hinter ihm her.',
      'Reduziert nach ein paar Tagen auf eine Hand.',
      'Vermeidet Ziehen an den Armen.',
    ],
    durationMin: 8,
  },
]
