import type { Exercise } from './types'

/** Zusätzliche Übungen für Kreativität, Denken und Miteinander. */
export const CREATIVE_EXERCISES: Exercise[] = [
  {
    id: 'kr-schwamm-drucken',
    title: 'Mit Schwämmen drucken',
    fromWeeks: 100,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Formen erzeugen und Material erforschen.',
    material: 'Schwammstücke, Fingerfarbe, Papier',
    steps: [
      'Schneidet Schwämme in einfache Formen.',
      'Tupft sie in Farbe und druckt einmal vor.',
      'Lasst euer Kind selbst drucken.',
      'Benennt die entstandenen Formen.',
    ],
    durationMin: 15,
  },
  {
    id: 'kr-kleben',
    title: 'Kleben ohne Vorgabe',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Feinmotorik und freies Gestalten.',
    material: 'Klebestift, Papierschnipsel, ein Blatt',
    steps: [
      'Reißt gemeinsam Papier in Stücke.',
      'Zeigt, wie der Klebestift funktioniert.',
      'Lasst euer Kind frei kleben, ohne Motivvorgabe.',
      'Hängt das Ergebnis auf.',
    ],
    durationMin: 15,
  },
  {
    id: 'kr-hoehle-bauen',
    title: 'Eine Höhle bauen',
    fromWeeks: 100,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Rückzugsort schaffen und gemeinsam planen.',
    material: 'Decken, Stühle, Wäscheklammern',
    steps: [
      'Baut gemeinsam ein Dach über zwei Stühle.',
      'Lasst euer Kind entscheiden, wo der Eingang ist.',
      'Legt Kissen und ein Buch hinein.',
      'Lasst die Höhle einen Tag stehen.',
    ],
    durationMin: 25,
  },
  {
    id: 'kr-musikinstrumente',
    title: 'Instrumente aus der Küche',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Klänge erzeugen und unterscheiden.',
    material: 'Töpfe, Holzlöffel, eine verschlossene Dose mit Reis',
    steps: [
      'Baut gemeinsam drei Instrumente.',
      'Probiert alle Klänge aus.',
      'Spielt zu einem Lied im Takt mit.',
      'Räumt danach gemeinsam weg.',
    ],
    durationMin: 15,
  },
  {
    id: 'kr-schattenspiel',
    title: 'Schattenfiguren',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Zusammenhang zwischen Hand und Schatten begreifen.',
    material: 'Eine Lampe, eine helle Wand',
    steps: [
      'Verdunkelt den Raum und richtet die Lampe auf die Wand.',
      'Macht eine einfache Figur mit der Hand.',
      'Lasst euer Kind eigene Formen probieren.',
      'Erfindet eine kurze Geschichte dazu.',
    ],
    durationMin: 12,
  },
  {
    id: 'kr-sortieren-loeffel',
    title: 'Besteck einsortieren',
    fromWeeks: 100,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Kategorien bilden und im Haushalt helfen.',
    material: 'Ein Besteckkasten, unbedenkliches Besteck',
    steps: [
      'Nehmt Löffel und Gabeln, keine Messer.',
      'Sortiert die ersten gemeinsam ein.',
      'Lasst euer Kind weitermachen.',
      'Macht es zu einer festen Aufgabe nach dem Abwasch.',
    ],
    durationMin: 10,
  },
  {
    id: 'kr-naturbild',
    title: 'Bild aus Naturmaterial',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Gesammeltes weiterverarbeiten und gestalten.',
    material: 'Blätter, Zapfen, Kleber, Papier',
    steps: [
      'Legt die Fundstücke auf das Papier.',
      'Lasst euer Kind die Anordnung bestimmen.',
      'Klebt gemeinsam fest.',
      'Schreibt Datum und Fundort darauf.',
    ],
    durationMin: 20,
  },
  {
    id: 'kr-was-fehlt',
    title: 'Was fehlt?',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Gedächtnis und genaues Hinschauen.',
    material: 'Drei bekannte Gegenstände, ein Tuch',
    steps: [
      'Legt drei Gegenstände hin und benennt sie.',
      'Deckt sie ab und nehmt einen weg.',
      'Fragt, welcher fehlt.',
      'Steigert auf vier, wenn drei leicht fallen.',
    ],
    durationMin: 10,
  },
  {
    id: 'kr-kneten-formen',
    title: 'Formen aus Knete',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Feinmotorik und Vorstellungskraft.',
    material: 'Knete, Ausstechformen',
    steps: [
      'Rollt gemeinsam eine Platte aus.',
      'Zeigt einmal das Ausstechen.',
      'Lasst euer Kind selbst wählen und ausstechen.',
      'Benennt die entstandenen Formen.',
    ],
    durationMin: 15,
  },
  {
    id: 'kr-geschichte-bilder',
    title: 'Bildergeschichte legen',
    fromWeeks: 130,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Reihenfolgen und Zusammenhänge verstehen.',
    material: 'Drei Fotos einer bekannten Abfolge',
    steps: [
      'Fotografiert drei Schritte eines Alltagsablaufs.',
      'Legt die Bilder gemischt hin.',
      'Lasst euer Kind sie in die richtige Reihenfolge bringen.',
      'Erzählt gemeinsam die Geschichte dazu.',
    ],
    durationMin: 12,
  },
  {
    id: 'kr-verkleiden',
    title: 'Verkleiden',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Rollen ausprobieren und An- und Ausziehen üben.',
    material: 'Alte Kleidung, Hüte, Tücher',
    steps: [
      'Stellt eine Kiste mit Verkleidungssachen bereit.',
      'Verkleidet euch selbst mit.',
      'Spielt eine kurze Szene.',
      'Fotografiert das Ergebnis.',
    ],
    durationMin: 20,
  },
  {
    id: 'kr-bauen-frei',
    title: 'Frei bauen ohne Anleitung',
    fromWeeks: 90,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Eigene Ideen umsetzen statt Vorlagen kopieren.',
    material: 'Bausteine',
    steps: [
      'Schüttet die Steine aus und setzt euch dazu.',
      'Baut selbst etwas, ohne Anweisungen zu geben.',
      'Fragt, was euer Kind gebaut hat.',
      'Lasst das Bauwerk stehen, wenn es möglich ist.',
    ],
    durationMin: 20,
  },
  {
    id: 'kr-lieder-erfinden',
    title: 'Eigene Lieder erfinden',
    fromWeeks: 100,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Sprachspiel und Kreativität.',
    material: 'Nichts',
    steps: [
      'Nehmt eine bekannte Melodie.',
      'Ersetzt den Text durch etwas aus eurem Alltag.',
      'Lasst euer Kind Wörter beisteuern.',
      'Singt das Lied über Wochen weiter.',
    ],
    durationMin: 8,
  },
  {
    id: 'kr-post-spiel',
    title: 'Briefkasten spielen',
    fromWeeks: 90,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Einwerfen üben und Rollenspiel verbinden.',
    material: 'Ein Karton mit Schlitz, Papierkarten',
    steps: [
      'Schneidet einen Schlitz in einen Schuhkarton.',
      'Zeigt, wie eine Karte hineinfällt.',
      'Lasst euer Kind Post einwerfen.',
      'Öffnet den Karton gemeinsam und leert ihn.',
    ],
    durationMin: 12,
  },
  {
    id: 'kr-farbe-mischen',
    title: 'Farben mischen',
    fromWeeks: 130,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Ursache und Wirkung im Kreativen erleben.',
    material: 'Zwei Farben, ein Teller',
    steps: [
      'Gebt zwei Farbkleckse nebeneinander.',
      'Rührt einen kleinen Teil zusammen.',
      'Fragt, was passiert ist.',
      'Lasst euer Kind weitere Kombinationen probieren.',
    ],
    durationMin: 15,
  },
  {
    id: 'kr-tisch-decken-selbst',
    title: 'Den eigenen Platz decken',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Verantwortung für einen konkreten Bereich.',
    material: 'Unzerbrechliches Geschirr, ein Platzset als Vorlage',
    steps: [
      'Zeichnet auf ein Platzset die Umrisse von Teller, Becher und Löffel.',
      'Lasst euer Kind das Geschirr darauflegen.',
      'Übt es täglich vor dem Essen.',
      'Lobt das Mitmachen.',
    ],
    durationMin: 8,
  },
  {
    id: 'kr-blumen-pressen',
    title: 'Blätter pressen',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Geduld über mehrere Tage erleben.',
    material: 'Gesammelte Blätter, ein schweres Buch, Papier',
    steps: [
      'Legt die Blätter zwischen zwei Blätter Papier.',
      'Beschwert sie mit einem Buch.',
      'Wartet gemeinsam mehrere Tage.',
      'Klebt die gepressten Blätter auf ein Blatt.',
    ],
    durationMin: 15,
  },
  {
    id: 'kr-selbstportraet',
    title: 'Sich selbst malen',
    fromWeeks: 140,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Körperschema und Selbstbild.',
    material: 'Papier, Stifte, ein Spiegel',
    steps: [
      'Schaut gemeinsam in den Spiegel und benennt Körperteile.',
      'Lasst euer Kind sich selbst malen.',
      'Fragt nach, was welcher Teil ist.',
      'Schreibt das Datum dazu und hebt es auf.',
    ],
    durationMin: 15,
  },
  {
    id: 'kr-wiederholung-lieblingsbuch',
    title: 'Das gleiche Buch, immer wieder',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Vertiefung durch Wiederholung – genau darum bitten Kinder darum.',
    material: 'Das Lieblingsbuch',
    steps: [
      'Lest dasselbe Buch, so oft es gewünscht wird.',
      'Lasst euer Kind bekannte Stellen mitsprechen.',
      'Haltet vor bekannten Wörtern an.',
      'Widersteht dem Drang, ein neues Buch vorzuschlagen.',
    ],
    durationMin: 10,
  },
  {
    id: 'kr-tag-fotografieren',
    title: 'Der Tag in drei Fotos',
    fromWeeks: 130,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Erinnerung, Auswahl und Erzählen verbinden.',
    material: 'Ein Handy oder eine einfache Kamera',
    steps: [
      'Lasst euer Kind drei Dinge fotografieren, die ihm wichtig waren.',
      'Schaut die Bilder abends gemeinsam an.',
      'Lasst es dazu erzählen.',
      'Speichert die Bilder in einem eigenen Album.',
    ],
    durationMin: 15,
  },
]
