import type { Exercise } from './types'

/** Übungen, die sich in bestehende Alltagsabläufe einbauen lassen. */
export const EVERYDAY_EXERCISES: Exercise[] = [
  {
    id: 'ev-wickeln-fingerspiel',
    title: 'Fingerspiel beim Wickeln',
    fromWeeks: 4,
    toWeeks: 104,
    area: 'sprache',
    goal: 'Aus einer Pflichtsituation eine Sprachsituation machen.',
    material: 'Nichts',
    steps: [
      'Wählt ein kurzes Fingerspiel, das immer beim Wickeln kommt.',
      'Macht die Bewegungen an den Zehen oder am Bauch.',
      'Macht vor dem Ende eine Pause.',
      'Bleibt monatelang beim selben Spiel.',
    ],
    durationMin: 3,
  },
  {
    id: 'ev-anziehen-benennen',
    title: 'Kleidung benennen',
    fromWeeks: 20,
    toWeeks: 130,
    area: 'sprache',
    goal: 'Wortschatz im Alltag aufbauen.',
    material: 'Kleidung',
    steps: [
      'Benennt jedes Kleidungsstück, bevor ihr es anzieht.',
      'Sagt dazu den Körperteil: "Socke auf den Fuß."',
      'Wartet kurz vor jedem Schritt.',
      'Fragt später: "Wo ist die Mütze?"',
    ],
    durationMin: 5,
  },
  {
    id: 'ev-essen-gemeinsam',
    title: 'Gemeinsam am Tisch essen',
    fromWeeks: 24,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Essverhalten und Sprache lernen durch Zuschauen.',
    material: 'Ein Hochstuhl am Familientisch',
    steps: [
      'Setzt euer Kind zu jeder Mahlzeit mit an den Tisch.',
      'Esst gleichzeitig, nicht nacheinander.',
      'Sprecht über das Essen, nicht über das Essverhalten.',
      'Lasst es selbst entscheiden, wie viel es isst.',
    ],
    durationMin: 25,
  },
  {
    id: 'ev-einkauf-benennen',
    title: 'Der sprechende Einkauf',
    fromWeeks: 30,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Wortschatz in echten Zusammenhängen aufbauen.',
    material: 'Nichts',
    steps: [
      'Benennt jedes Produkt, das ihr in den Wagen legt.',
      'Lasst euer Kind Dinge anfassen, die unbedenklich sind.',
      'Fragt ab einem Jahr: "Wo sind die Äpfel?"',
      'Beschreibt Farben und Formen.',
    ],
    durationMin: 20,
  },
  {
    id: 'ev-baden-schuetten',
    title: 'Badewanne als Labor',
    fromWeeks: 26,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Materialerfahrung ohne zusätzlichen Aufwand.',
    material: 'Becher, Sieb, Schwamm',
    steps: [
      'Legt drei Gefäße mit unterschiedlichen Eigenschaften dazu.',
      'Zeigt, wie das Sieb Wasser durchlässt.',
      'Lasst euer Kind selbst probieren.',
      'Nie unbeaufsichtigt, auch nicht kurz.',
    ],
    durationMin: 15,
  },
  {
    id: 'ev-abendritual',
    title: 'Das immer gleiche Abendritual',
    fromWeeks: 8,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Einschlafen durch Vorhersehbarkeit erleichtern.',
    material: 'Nichts',
    steps: [
      'Legt eine feste Reihenfolge fest: Bad, Schlafanzug, Buch, Lied, Licht aus.',
      'Haltet die Reihenfolge jeden Abend ein, auch unterwegs.',
      'Haltet sie kurz, zwanzig bis dreißig Minuten reichen.',
      'Beide Elternteile machen sie gleich.',
    ],
    durationMin: 25,
  },
  {
    id: 'ev-aufwachen-begruessen',
    title: 'Immer gleich begrüßen',
    fromWeeks: 4,
    toWeeks: 104,
    area: 'sozial',
    goal: 'Übergänge vom Schlaf ins Wachsein sanft gestalten.',
    material: 'Nichts',
    steps: [
      'Sagt beim Betreten des Zimmers immer denselben Satz.',
      'Öffnet die Vorhänge und benennt den Tag.',
      'Lasst eurem Kind Zeit zum Wachwerden, bevor ihr es hochnehmt.',
      'Beide Elternteile nutzen denselben Satz.',
    ],
    durationMin: 3,
  },
  {
    id: 'ev-autofahrt-singen',
    title: 'Autofahrt mit Liedern',
    fromWeeks: 8,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Fahrten überbrücken und dabei Sprachrhythmus üben.',
    material: 'Nichts',
    steps: [
      'Legt zwei bis drei feste Autolieder fest.',
      'Singt sie in derselben Reihenfolge.',
      'Lasst euer Kind ab etwa einem Jahr das Lied wählen.',
      'Verzichtet auf Bildschirme im Auto.',
    ],
    durationMin: 10,
  },
  {
    id: 'ev-schuhe-anziehen-platz',
    title: 'Ein eigener Platz für Schuhe',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Ordnung und Selbstständigkeit im Alltag.',
    material: 'Eine niedrige Ablage',
    steps: [
      'Richtet einen erreichbaren Platz für Schuhe und Jacke ein.',
      'Zeigt einmal, wohin was gehört.',
      'Fragt beim Nachhausekommen, wo die Schuhe hingehören.',
      'Räumt gemeinsam auf, statt es einzufordern.',
    ],
    durationMin: 5,
  },
  {
    id: 'ev-kochen-zuschauen',
    title: 'Beim Kochen dabei sein',
    fromWeeks: 30,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Teilhabe statt Beschäftigung.',
    material: 'Ein sicherer Platz in Sichtweite',
    steps: [
      'Setzt oder stellt euer Kind so, dass es zusehen kann.',
      'Beschreibt, was ihr tut.',
      'Gebt ihm eine eigene Schüssel und einen Löffel.',
      'Lasst es ab etwa zwei Jahren echte kleine Aufgaben übernehmen.',
    ],
    durationMin: 20,
  },
  {
    id: 'ev-warten-beschaeftigen',
    title: 'Wartezeit überbrücken',
    fromWeeks: 52,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Wartesituationen ohne Bildschirm bewältigen.',
    material: 'Nichts',
    steps: [
      'Sucht gemeinsam nach etwas Rotem im Raum.',
      'Zählt Dinge, die ihr seht.',
      'Erfindet Geschichten über andere Wartende.',
      'Habt einen kleinen Gegenstand in der Tasche für den Notfall.',
    ],
    durationMin: 10,
  },
  {
    id: 'ev-uebergabe-ritual',
    title: 'Übergabe zwischen den Eltern',
    fromWeeks: 4,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Wechsel zwischen den Bezugspersonen berechenbar machen.',
    material: 'Nichts',
    steps: [
      'Legt einen kurzen festen Ablauf für die Übergabe fest.',
      'Verabschiedet euch immer, auch wenn es Tränen gibt.',
      'Bleibt kurz, verlängert den Abschied nicht.',
      'Erzählt danach kurz, was in eurer Zeit passiert ist.',
    ],
    durationMin: 5,
  },
  {
    id: 'ev-nachtwache-ruhig',
    title: 'Die ruhige Nachtwache',
    fromWeeks: 0,
    toWeeks: 104,
    area: 'alltag',
    goal: 'Nächtliche Wachphasen kurz halten.',
    material: 'Ein gedimmtes Licht',
    steps: [
      'Haltet das Licht so dunkel wie möglich.',
      'Sprecht nicht oder nur flüsternd.',
      'Erledigt nur das Nötige, kein Spielen.',
      'Legt euer Kind wieder hin, sobald es geht.',
    ],
    durationMin: 10,
  },
  {
    id: 'ev-fotobuch-eigenes',
    title: 'Ein eigenes Fotobuch',
    fromWeeks: 40,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Personen und Erlebnisse benennen und wiedererkennen.',
    material: 'Ausgedruckte Fotos, ein kleines Album',
    steps: [
      'Wählt zehn Fotos von vertrauten Personen und Orten.',
      'Steckt sie in ein robustes Album.',
      'Benennt beim Durchblättern jede Person.',
      'Tauscht die Fotos alle paar Monate.',
    ],
    durationMin: 10,
  },
  {
    id: 'ev-wetterfest-raus',
    title: 'Bei jedem Wetter raus',
    fromWeeks: 2,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Bewegung, Licht und besserer Schlaf.',
    material: 'Passende Kleidung',
    steps: [
      'Geht täglich raus, unabhängig vom Wetter.',
      'Zieht euer Kind wettergerecht an, nicht zu warm.',
      'Lasst es ab dem Laufalter selbst gehen, auch wenn es langsamer ist.',
      'Zwanzig Minuten reichen an schlechten Tagen.',
    ],
    durationMin: 20,
  },
  {
    id: 'ev-mahlzeit-ankuendigen',
    title: 'Übergänge ankündigen',
    fromWeeks: 52,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Konflikte bei Wechseln reduzieren.',
    material: 'Nichts',
    steps: [
      'Kündigt jeden Wechsel zwei Minuten vorher an.',
      'Nennt, was als Nächstes kommt.',
      'Gebt eine konkrete Restmenge an: "Noch zweimal rutschen."',
      'Haltet euch selbst an die Ankündigung.',
    ],
    durationMin: 2,
  },
  {
    id: 'ev-vorlesen-taeglich',
    title: 'Jeden Tag vorlesen',
    fromWeeks: 12,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Wortschatz, Konzentration und Nähe in einem.',
    material: 'Bücher',
    steps: [
      'Legt eine feste Vorlesezeit fest.',
      'Lest dasselbe Buch so oft, wie gewünscht.',
      'Zeigt beim Lesen auf die Bilder.',
      'Hört auf, wenn das Interesse endet, nicht am Buchende.',
    ],
    durationMin: 12,
  },
  {
    id: 'ev-aufraeumlied',
    title: 'Das Aufräumlied',
    fromWeeks: 52,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Aufräumen ohne Streit einleiten.',
    material: 'Nichts',
    steps: [
      'Wählt ein kurzes Lied, das nur beim Aufräumen gesungen wird.',
      'Beginnt selbst zu singen und zu räumen.',
      'Macht mit, statt zu beaufsichtigen.',
      'Beendet, wenn das Lied zu Ende ist, auch wenn nicht alles fertig ist.',
    ],
    durationMin: 5,
  },
  {
    id: 'ev-erste-hilfe-kasten',
    title: 'Vorbereitet sein',
    fromWeeks: 0,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Im Ernstfall handlungsfähig sein statt zu suchen.',
    material: 'Fieberthermometer, Nasentropfen, Fiebermittel, Pflaster',
    steps: [
      'Legt alles an einen festen Platz, den beide kennen.',
      'Notiert Notrufnummern gut sichtbar.',
      'Prüft Haltbarkeitsdaten zweimal im Jahr.',
      'Macht einen Erste-Hilfe-Kurs für Säuglinge und Kleinkinder.',
    ],
    durationMin: 15,
  },
  {
    id: 'ev-schlafumgebung',
    title: 'Sichere Schlafumgebung prüfen',
    fromWeeks: 0,
    toWeeks: 78,
    area: 'alltag',
    goal: 'Das Risiko für den plötzlichen Kindstod senken.',
    material: 'Nichts',
    steps: [
      'Auf dem Rücken schlafen lassen, im eigenen Bett im Elternschlafzimmer.',
      'Feste Matratze, kein Kissen, keine Decke, keine Kuscheltiere.',
      'Raumtemperatur um 18 Grad, Schlafsack statt Decke.',
      'Rauchfreie Umgebung, auch auf der Kleidung.',
    ],
    durationMin: 10,
  },
]
