import type { Exercise } from './types'

/** Übungen für den vierten bis sechsten Monat (Woche 13 bis 26). */
export const INFANT_EXERCISES: Exercise[] = [
  {
    id: 'in-greifen-uebergabe',
    title: 'Von Hand zu Hand',
    fromWeeks: 16,
    toWeeks: 34,
    area: 'motorik',
    goal: 'Beide Körperhälften zur Zusammenarbeit bringen.',
    material: 'Ein leichtes Greifspielzeug',
    steps: [
      'Gebt eurem Kind das Spielzeug in eine Hand.',
      'Haltet die andere Hand frei und wartet.',
      'Zeigt bei Bedarf einmal, wie das Übergeben geht.',
      'Lasst es selbst probieren, auch wenn es mehrfach fällt.',
    ],
    durationMin: 6,
  },
  {
    id: 'in-kuckuck',
    title: 'Kuckuck',
    fromWeeks: 16,
    toWeeks: 78,
    area: 'kognition',
    goal: 'Die Objektpermanenz aufbauen: Was weg ist, ist nicht verschwunden.',
    material: 'Ein Tuch',
    steps: [
      'Haltet euch das Tuch vors Gesicht.',
      'Wartet zwei Sekunden, zieht es weg und sagt "Kuckuck".',
      'Wiederholt es mehrmals mit gleichem Rhythmus.',
      'Später: das Tuch über das Gesicht des Kindes legen und ziehen lassen.',
    ],
    durationMin: 5,
  },
  {
    id: 'in-drehen-anregen',
    title: 'Zum Drehen locken',
    fromWeeks: 14,
    toWeeks: 30,
    area: 'motorik',
    goal: 'Die Drehung vom Rücken auf den Bauch anbahnen.',
    material: 'Ein interessantes Spielzeug',
    steps: [
      'Legt euer Kind auf den Rücken.',
      'Haltet das Spielzeug seitlich, knapp außerhalb der Reichweite.',
      'Bewegt es langsam weiter zur Seite, sodass sich der Kopf mitdreht.',
      'Helft am Ende minimal an der Hüfte, wenn es fast geschafft ist.',
    ],
    durationMin: 6,
  },
  {
    id: 'in-fuss-mund',
    title: 'Füße zum Mund',
    fromWeeks: 16,
    toWeeks: 30,
    area: 'motorik',
    goal: 'Bauchmuskulatur stärken und Körperschema erweitern.',
    material: 'Nichts',
    steps: [
      'Legt euer Kind auf den Rücken.',
      'Führt einen Fuß sanft in Richtung Mund.',
      'Lasst los und schaut, ob es die Bewegung übernimmt.',
      'Wechselt die Seite, ohne zu drängen.',
    ],
    durationMin: 4,
  },
  {
    id: 'in-becher-stapeln',
    title: 'Becher ineinander',
    fromWeeks: 24,
    toWeeks: 78,
    area: 'kognition',
    goal: 'Größenverhältnisse begreifen und Feinmotorik üben.',
    material: 'Drei bis fünf Stapelbecher',
    steps: [
      'Stellt die Becher offen vor euer Kind.',
      'Steckt einmal zwei ineinander und zieht sie wieder auseinander.',
      'Gebt sie eurem Kind und lasst es probieren.',
      'Kommentiert, was passiert, statt zu korrigieren.',
    ],
    durationMin: 10,
  },
  {
    id: 'in-loeffel-halten',
    title: 'Eigener Löffel',
    fromWeeks: 22,
    toWeeks: 60,
    area: 'alltag',
    goal: 'Selbstständiges Essen anbahnen.',
    material: 'Zwei Kinderlöffel',
    steps: [
      'Gebt eurem Kind einen eigenen Löffel in die Hand.',
      'Füttert mit dem zweiten Löffel weiter.',
      'Lasst zu, dass der eigene Löffel im Mund oder im Brei landet.',
      'Räumt hinterher auf, ohne währenddessen zu wischen.',
    ],
    durationMin: 15,
  },
  {
    id: 'in-bilderbuch-hart',
    title: 'Erstes Bilderbuch',
    fromWeeks: 20,
    toWeeks: 104,
    area: 'sprache',
    goal: 'Sprache und Bild verknüpfen, Seiten umblättern üben.',
    material: 'Ein Pappbilderbuch mit klaren Motiven',
    steps: [
      'Setzt euer Kind auf euren Schoß, das Buch vor euch.',
      'Zeigt auf ein Bild und benennt es klar.',
      'Lasst euer Kind umblättern, auch wenn es zwei Seiten auf einmal nimmt.',
      'Hört auf, wenn das Interesse endet, nicht wenn das Buch endet.',
    ],
    durationMin: 6,
  },
  {
    id: 'in-schaukeltuch',
    title: 'Im Tuch schaukeln',
    fromWeeks: 16,
    toWeeks: 52,
    area: 'sinne',
    goal: 'Gleichgewichtssinn und Körperwahrnehmung anregen.',
    material: 'Eine stabile Decke, zwei Erwachsene',
    steps: [
      'Legt euer Kind in die Mitte der Decke.',
      'Fasst beide je zwei Ecken und hebt sie knapp über den Boden.',
      'Schaukelt langsam hin und her, singt dazu.',
      'Bleibt tief über dem Boden und beendet bei Unbehagen.',
    ],
    durationMin: 5,
  },
  {
    id: 'in-geraeusche-machen',
    title: 'Geräusche selbst erzeugen',
    fromWeeks: 20,
    toWeeks: 60,
    area: 'kognition',
    goal: 'Ursache und Wirkung erfahren.',
    material: 'Ein Topfdeckel und ein Holzlöffel',
    steps: [
      'Zeigt einmal, wie das Klopfen klingt.',
      'Gebt eurem Kind den Löffel in die Hand.',
      'Haltet den Deckel in Reichweite.',
      'Lasst es so lange klopfen, wie ihr es aushaltet.',
    ],
    durationMin: 8,
  },
  {
    id: 'in-rollen-uebung',
    title: 'Über den Boden rollen',
    fromWeeks: 20,
    toWeeks: 40,
    area: 'motorik',
    goal: 'Die Drehbewegung in beide Richtungen automatisieren.',
    material: 'Eine Decke auf festem Boden',
    steps: [
      'Legt euer Kind auf den Rücken.',
      'Rollt es langsam über die Seite auf den Bauch, dann weiter.',
      'Macht das Spiel mit Geräuschen und Lachen.',
      'Lasst es zunehmend selbst übernehmen.',
    ],
    durationMin: 6,
  },
  {
    id: 'in-sitzen-stuetzen',
    title: 'Sitzen mit Stütze',
    fromWeeks: 20,
    toWeeks: 34,
    area: 'motorik',
    goal: 'Rumpfmuskulatur für das freie Sitzen aufbauen.',
    material: 'Ein Stillkissen oder zwei feste Polster',
    steps: [
      'Setzt euer Kind so, dass die Polster den Rücken und die Seiten stützen.',
      'Legt Spielzeug in Reichweite vor die Hände.',
      'Bleibt in Griffweite, das Umkippen kommt schnell.',
      'Fünf Minuten reichen anfangs.',
    ],
    durationMin: 6,
  },
  {
    id: 'in-versteckte-dinge',
    title: 'Halb versteckt',
    fromWeeks: 24,
    toWeeks: 52,
    area: 'kognition',
    goal: 'Den Schritt zur vollständigen Objektpermanenz machen.',
    material: 'Ein Tuch und ein Lieblingsspielzeug',
    steps: [
      'Legt das Spielzeug vor euer Kind.',
      'Deckt es zur Hälfte mit dem Tuch ab.',
      'Wartet, ob euer Kind danach greift.',
      'Deckt es später vollständig ab, wenn das gelingt.',
    ],
    durationMin: 6,
  },
  {
    id: 'in-namen-rufen',
    title: 'Rufen aus dem Nebenraum',
    fromWeeks: 24,
    toWeeks: 78,
    area: 'sprache',
    goal: 'Auf den eigenen Namen reagieren, auch ohne Blickkontakt.',
    material: 'Nichts',
    steps: [
      'Ruft den Namen eures Kindes aus einem anderen Zimmer.',
      'Wartet auf eine Reaktion – Innehalten, Kopfdrehen, Lauten.',
      'Kommt herein und zeigt Freude.',
      'Nicht mehr als zwei- bis dreimal am Tag, sonst nutzt es sich ab.',
    ],
    durationMin: 3,
  },
  {
    id: 'in-wasserspiel',
    title: 'Planschen in der Wanne',
    fromWeeks: 20,
    toWeeks: 104,
    area: 'sinne',
    goal: 'Wasser als Material erfahren, Arme und Hände kräftigen.',
    material: 'Badewanne, ein Becher',
    steps: [
      'Setzt euer Kind sicher gestützt ins flache Wasser.',
      'Zeigt, wie man mit dem Becher schöpft und gießt.',
      'Lasst es selbst probieren und spritzen.',
      'Nie aus den Augen lassen, auch nicht für Sekunden.',
    ],
    durationMin: 12,
  },
  {
    id: 'in-krabbeln-anbahnen',
    title: 'Vierfüßler unterstützen',
    fromWeeks: 24,
    toWeeks: 40,
    area: 'motorik',
    goal: 'Den Vierfüßlerstand vorbereiten.',
    material: 'Ein zusammengerolltes Handtuch',
    steps: [
      'Legt euer Kind in Bauchlage.',
      'Schiebt die Rolle unter den Bauch, sodass Hände und Knie Kontakt haben.',
      'Legt ein Spielzeug knapp außer Reichweite.',
      'Unterstützt nur so viel wie nötig.',
    ],
    durationMin: 6,
  },
  {
    id: 'in-tastbuch',
    title: 'Fühlbuch',
    fromWeeks: 20,
    toWeeks: 78,
    area: 'sinne',
    goal: 'Tastsinn und Sprache verbinden.',
    material: 'Ein Fühlbuch oder selbst gebastelte Stoffkarten',
    steps: [
      'Führt die Hand eures Kindes über die Fläche.',
      'Benennt die Eigenschaft: weich, rau, glatt.',
      'Lasst es selbst tasten und beobachtet die Vorlieben.',
      'Wiederholt dieselben Wörter über Wochen.',
    ],
    durationMin: 6,
  },
  {
    id: 'in-hochziehen-haende',
    title: 'An den Händen aufsetzen',
    fromWeeks: 18,
    toWeeks: 34,
    area: 'motorik',
    goal: 'Bauch- und Nackenmuskulatur kräftigen.',
    material: 'Nichts',
    steps: [
      'Legt euer Kind auf den Rücken und gebt ihm eure Daumen zum Greifen.',
      'Zieht ganz langsam, bis der Kopf mitkommt.',
      'Achtet darauf, dass der Kopf nicht zurückfällt – dann ist es noch zu früh.',
      'Legt es ebenso langsam wieder ab.',
    ],
    durationMin: 4,
  },
  {
    id: 'in-fingerfood',
    title: 'Erstes Fingerfood',
    fromWeeks: 24,
    toWeeks: 60,
    area: 'alltag',
    goal: 'Selbstständiges Essen und Pinzettengriff üben.',
    material: 'Weich gedämpfte Gemüsestifte',
    steps: [
      'Schneidet Karotte oder Pastinake in fingerlange Stifte.',
      'Dämpft sie, bis sie sich zwischen den Fingern zerdrücken lassen.',
      'Legt zwei bis drei Stücke direkt vor euer Kind.',
      'Bleibt daneben sitzen und greift nicht in den Mund.',
    ],
    durationMin: 15,
  },
  {
    id: 'in-musik-bewegung',
    title: 'Musik und Wiegen',
    fromWeeks: 16,
    toWeeks: 104,
    area: 'sinne',
    goal: 'Rhythmusgefühl und gemeinsame Freude.',
    material: 'Musik',
    steps: [
      'Nehmt euer Kind auf den Arm.',
      'Bewegt euch im Takt, betont deutlich den Rhythmus.',
      'Wechselt zwischen schnell und langsam.',
      'Beobachtet, welche Musik die stärkste Reaktion auslöst.',
    ],
    durationMin: 8,
  },
  {
    id: 'in-ball-rollen',
    title: 'Ball hin und her',
    fromWeeks: 26,
    toWeeks: 104,
    area: 'sozial',
    goal: 'Abwechseln lernen – die Grundlage von Gesprächen und Spielen.',
    material: 'Ein weicher Ball',
    steps: [
      'Setzt euch mit gespreizten Beinen gegenüber.',
      'Rollt den Ball langsam zu eurem Kind.',
      'Wartet, bis es ihn zurückschiebt, helft anfangs nach.',
      'Benennt jedes Mal: "Zu dir – zu mir."',
    ],
    durationMin: 8,
  },
  {
    id: 'in-papier-knuellen',
    title: 'Papier knüllen',
    fromWeeks: 24,
    toWeeks: 60,
    area: 'motorik',
    goal: 'Handkraft aufbauen und Geräusche erforschen.',
    material: 'Ein Bogen Backpapier oder Zeitungspapier',
    steps: [
      'Zeigt, wie das Papier knistert.',
      'Gebt eurem Kind ein Stück in die Hand.',
      'Lasst es knüllen, ziehen und reißen.',
      'Bleibt dabei – Papier landet im Mund.',
    ],
    durationMin: 6,
  },
  {
    id: 'in-spiegelspiel',
    title: 'Bewegungen im Spiegel',
    fromWeeks: 24,
    toWeeks: 104,
    area: 'sozial',
    goal: 'Sich selbst und andere im Spiegel unterscheiden lernen.',
    material: 'Ein großer Spiegel',
    steps: [
      'Setzt euch gemeinsam vor den Spiegel.',
      'Winkt, klatscht, macht Grimassen.',
      'Beschreibt, was ihr seht.',
      'Berührt euer Spiegelbild und dann euch selbst.',
    ],
    durationMin: 6,
  },
  {
    id: 'in-hindernis-kissen',
    title: 'Kissenberg',
    fromWeeks: 26,
    toWeeks: 78,
    area: 'motorik',
    goal: 'Krabbeln über unebenen Untergrund üben.',
    material: 'Zwei bis drei feste Kissen',
    steps: [
      'Legt die Kissen flach nebeneinander auf den Boden.',
      'Setzt euch dahinter und lockt euer Kind zu euch.',
      'Helft nur, wenn es feststeckt.',
      'Erhöht den Schwierigkeitsgrad langsam.',
    ],
    durationMin: 10,
  },
  {
    id: 'in-taschentuchbox',
    title: 'Tücher herausziehen',
    fromWeeks: 24,
    toWeeks: 60,
    area: 'motorik',
    goal: 'Zug- und Greifbewegung üben, mit sofortiger Belohnung.',
    material: 'Eine leere Tücherbox, gefüllt mit Stofftüchern',
    steps: [
      'Steckt mehrere Tücher lose ineinander in die Box.',
      'Zieht eines heraus und zeigt, dass das nächste nachkommt.',
      'Gebt die Box eurem Kind.',
      'Füllt sie wieder, so oft es nötig ist.',
    ],
    durationMin: 10,
  },
  {
    id: 'in-benennen-alltag',
    title: 'Alles benennen',
    fromWeeks: 13,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Wortschatz aufbauen – der wirksamste Sprachförderer überhaupt.',
    material: 'Nichts',
    steps: [
      'Sprecht aus, was ihr gerade tut und seht.',
      'Nutzt einfache, klare Wörter statt Umschreibungen.',
      'Macht Pausen, damit euer Kind reagieren kann.',
      'Auch beim Kochen, Einkaufen und Aufräumen weitersprechen.',
    ],
    durationMin: 1,
  },
  {
    id: 'in-schaukelpferd-knie',
    title: 'Hoppe Reiter',
    fromWeeks: 20,
    toWeeks: 104,
    area: 'sozial',
    goal: 'Vorfreude und Erwartung erleben.',
    material: 'Nichts',
    steps: [
      'Setzt euer Kind auf eure Knie, haltet es sicher fest.',
      'Wippt im Rhythmus eines kurzen Reims.',
      'Macht vor der Pointe eine deutliche Pause.',
      'Lasst es am Ende sanft "fallen" – immer gleich.',
    ],
    durationMin: 5,
  },
  {
    id: 'in-holzloeffel-topf',
    title: 'Küchenschublade',
    fromWeeks: 26,
    toWeeks: 104,
    area: 'alltag',
    goal: 'Beim Kochen beschäftigt sein und dabei Material erforschen.',
    material: 'Eine untere Lade mit unbedenklichem Küchenzeug',
    steps: [
      'Räumt eine Lade frei und füllt sie mit Holzlöffeln, Schüsseln, Deckeln.',
      'Zeigt einmal, dass sie eurem Kind gehört.',
      'Lasst es ein- und ausräumen, während ihr kocht.',
      'Sichert alle anderen Laden.',
    ],
    durationMin: 15,
  },
  {
    id: 'in-hand-fuss-farbe',
    title: 'Hand- und Fußabdruck',
    fromWeeks: 13,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Materialerfahrung und eine bleibende Erinnerung.',
    material: 'Ungiftige Fingerfarbe, Papier',
    steps: [
      'Tragt etwas Farbe auf die Handfläche auf.',
      'Drückt die Hand auf das Papier.',
      'Beschreibt, was passiert.',
      'Sofort abwaschen und das Datum auf das Blatt schreiben.',
    ],
    durationMin: 10,
  },
]
