import type { Exercise } from './types'

/** Übungen mit Schwerpunkt Sprache und Miteinander. */
export const LANGUAGE_EXERCISES: Exercise[] = [
  {
    id: 'la-parallel-sprechen',
    title: 'Begleitendes Sprechen',
    fromWeeks: 0,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Wortschatz durch schiere Menge an gehörter Sprache aufbauen.',
    material: 'Nichts',
    steps: [
      'Sprecht aus, was ihr gerade tut, wie ein Kommentar.',
      'Nutzt kurze, klare Sätze.',
      'Macht Pausen für Reaktionen.',
      'Auch dann weitersprechen, wenn noch keine Antwort kommt.',
    ],
    durationMin: 1,
  },
  {
    id: 'la-erweitern',
    title: 'Antwort erweitern',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Vom Wort zum Satz kommen.',
    material: 'Nichts',
    steps: [
      'Wartet, bis euer Kind ein Wort sagt.',
      'Wiederholt es und fügt ein Wort hinzu: "Ball – ja, ein roter Ball."',
      'Korrigiert nicht, sondern erweitert.',
      'Bleibt bei einem Wort mehr, nicht bei fünf.',
    ],
    durationMin: 3,
  },
  {
    id: 'la-lied-mit-pausen',
    title: 'Lied mit Lücken',
    fromWeeks: 70,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Wörter aktiv abrufen.',
    material: 'Nichts',
    steps: [
      'Singt ein bekanntes Lied.',
      'Lasst das letzte Wort einer Zeile weg.',
      'Wartet, ob euer Kind ergänzt.',
      'Singt weiter, wenn nichts kommt.',
    ],
    durationMin: 6,
  },
  {
    id: 'la-wahl-anbieten',
    title: 'Zwei Möglichkeiten anbieten',
    fromWeeks: 70,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Sprechen fördern und Autonomie zulassen.',
    material: 'Nichts',
    steps: [
      'Haltet zwei Dinge hoch und benennt beide.',
      'Fragt: "Apfel oder Banane?"',
      'Wartet die Antwort ab, auch als Zeigen.',
      'Setzt die Wahl um, damit sie echt ist.',
    ],
    durationMin: 3,
  },
  {
    id: 'la-telefonieren',
    title: 'Telefonieren spielen',
    fromWeeks: 80,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Gesprächsstruktur ohne Blickkontakt üben.',
    material: 'Ein Spielzeugtelefon oder ein Baustein',
    steps: [
      'Haltet euch den Gegenstand ans Ohr und sagt "Hallo?"',
      'Führt ein kurzes Gespräch mit Pausen.',
      'Reicht das Telefon eurem Kind.',
      'Ruft später von einem echten Telefon an.',
    ],
    durationMin: 8,
  },
  {
    id: 'la-tageserzaehlung',
    title: 'Der Tag zum Nacherzählen',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Erinnerung und zusammenhängendes Erzählen.',
    material: 'Nichts',
    steps: [
      'Erzählt abends drei Dinge, die ihr erlebt habt.',
      'Fragt danach, was eurem Kind eingefallen ist.',
      'Helft mit konkreten Fragen statt mit "Was war heute?"',
      'Macht es zu einem festen Teil des Abendrituals.',
    ],
    durationMin: 8,
  },
  {
    id: 'la-buch-selber',
    title: 'Das Kind erzählt das Buch',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Vom Zuhören zum eigenen Erzählen.',
    material: 'Ein bekanntes Bilderbuch',
    steps: [
      'Nehmt ein Buch, das ihr oft gelesen habt.',
      'Bittet euer Kind, es euch zu erzählen.',
      'Hört zu, ohne zu korrigieren.',
      'Fragt nach, wenn es stockt.',
    ],
    durationMin: 10,
  },
  {
    id: 'la-nein-verstehen',
    title: 'Grenzen erklären',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Regeln nachvollziehbar machen.',
    material: 'Nichts',
    steps: [
      'Sagt, was nicht geht, und warum – in einem Satz.',
      'Bietet eine Alternative an.',
      'Bleibt bei der Grenze, auch bei Protest.',
      'Sprecht später noch einmal in Ruhe darüber.',
    ],
    durationMin: 3,
  },
  {
    id: 'la-dankeschoen',
    title: 'Bitte und danke vorleben',
    fromWeeks: 80,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Höflichkeit durch Vorbild statt durch Aufforderung.',
    material: 'Nichts',
    steps: [
      'Sagt selbst konsequent bitte und danke, auch zum Kind.',
      'Fordert es nicht ein.',
      'Freut euch, wenn es von selbst kommt.',
      'Nutzt es in echten Situationen, nicht als Übung.',
    ],
    durationMin: 1,
  },
  {
    id: 'la-fragen-beantworten',
    title: 'Warum-Fragen ernst nehmen',
    fromWeeks: 130,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Neugier als Lernmotor erhalten.',
    material: 'Nichts',
    steps: [
      'Beantwortet die Frage kurz und ehrlich.',
      'Sagt es, wenn ihr etwas nicht wisst.',
      'Schlagt gemeinsam nach oder schaut es euch an.',
      'Fragt zurück: "Was denkst du?"',
    ],
    durationMin: 5,
  },
  {
    id: 'la-zwei-sprachen',
    title: 'Zweisprachig konsequent',
    fromWeeks: 0,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Mehrsprachigkeit ohne Verwirrung aufbauen.',
    material: 'Nichts',
    steps: [
      'Jede Person spricht durchgehend ihre eigene Sprache.',
      'Wechselt nicht innerhalb eines Gesprächs.',
      'Rechnet mit einer Phase des Mischens – sie geht vorbei.',
      'Bietet in beiden Sprachen Bücher und Lieder an.',
    ],
    durationMin: 1,
  },
  {
    id: 'la-puppentheater',
    title: 'Kleines Puppentheater',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Situationen durchspielen und Sprache üben.',
    material: 'Zwei Stofftiere',
    steps: [
      'Lasst die Tiere miteinander sprechen.',
      'Spielt eine erlebte Situation nach.',
      'Gebt eurem Kind eines der Tiere.',
      'Übernehmt die Rolle, die es euch zuweist.',
    ],
    durationMin: 12,
  },
  {
    id: 'la-zuhoeren-ueben',
    title: 'Zuhören und wiederholen',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Aufmerksamkeit und Merkfähigkeit.',
    material: 'Nichts',
    steps: [
      'Sagt zwei Wörter und lasst sie wiederholen.',
      'Steigert auf drei, wenn es leicht fällt.',
      'Macht daraus einen Einkaufszettel im Spiel.',
      'Kurz halten, höchstens fünf Minuten.',
    ],
    durationMin: 6,
  },
  {
    id: 'la-gefuehl-spiegeln',
    title: 'Gefühle spiegeln',
    fromWeeks: 52,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Emotionsregulation über Benennen unterstützen.',
    material: 'Nichts',
    steps: [
      'Benennt das Gefühl, das ihr seht.',
      'Nennt den vermuteten Grund.',
      'Wartet, ohne sofort zu lösen.',
      'Bietet danach Trost oder Hilfe an.',
    ],
    durationMin: 3,
  },
  {
    id: 'la-abschied-ritual',
    title: 'Ein eigenes Abschiedsritual',
    fromWeeks: 30,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Trennungen berechenbar und dadurch leichter machen.',
    material: 'Nichts',
    steps: [
      'Erfindet einen kurzen festen Ablauf: zwei Küsse und Winken am Fenster.',
      'Macht ihn jedes Mal gleich.',
      'Verlängert ihn nicht bei Tränen.',
      'Geht danach zügig.',
    ],
    durationMin: 3,
  },
]
