import type { Exercise } from './types'

/** Zusätzliche Übungen mit Schwerpunkt Grob- und Feinmotorik. */
export const MOTOR_EXERCISES: Exercise[] = [
  {
    id: 'mo-arme-heben',
    title: 'Arme über den Kopf',
    fromWeeks: 12,
    toWeeks: 40,
    area: 'motorik',
    goal: 'Schultergürtel mobilisieren, Vorbereitung fürs Greifen nach oben.',
    material: 'Ein leichtes Tuch',
    steps: [
      'Legt euer Kind auf den Rücken.',
      'Führt das Tuch langsam über sein Blickfeld nach oben.',
      'Lasst es danach greifen.',
      'Wechselt zwischen beiden Seiten.',
    ],
    durationMin: 5,
  },
  {
    id: 'mo-seitenlage',
    title: 'Spielen in Seitenlage',
    fromWeeks: 10,
    toWeeks: 30,
    area: 'motorik',
    goal: 'Rumpfmuskulatur seitlich aktivieren.',
    material: 'Ein zusammengerolltes Handtuch',
    steps: [
      'Legt euer Kind auf die Seite, das Handtuch als Rückenstütze.',
      'Legt ein Spielzeug vor die Hände.',
      'Bleibt daneben und sprecht mit ihm.',
      'Wechselt nach ein paar Minuten die Seite.',
    ],
    durationMin: 6,
  },
  {
    id: 'mo-knie-schaukeln',
    title: 'Schaukeln im Vierfüßler',
    fromWeeks: 26,
    toWeeks: 45,
    area: 'motorik',
    goal: 'Gewichtsverlagerung fürs Krabbeln üben.',
    material: 'Nichts',
    steps: [
      'Bringt euer Kind in den Vierfüßlerstand.',
      'Schaukelt es sanft an der Hüfte vor und zurück.',
      'Lasst es dann selbst schaukeln.',
      'Legt ein Ziel in Blickrichtung.',
    ],
    durationMin: 6,
  },
  {
    id: 'mo-greifen-oben',
    title: 'Nach oben greifen',
    fromWeeks: 40,
    toWeeks: 90,
    area: 'motorik',
    goal: 'Streckung und Gleichgewicht im Stand.',
    material: 'Ein Spielzeug',
    steps: [
      'Lasst euer Kind sich an einem Möbel hochziehen.',
      'Haltet das Spielzeug knapp über Kopfhöhe.',
      'Lasst es danach greifen, mit einer Hand am Möbel.',
      'Bleibt in Griffweite.',
    ],
    durationMin: 8,
  },
  {
    id: 'mo-schieben-stuhl',
    title: 'Stuhl schieben',
    fromWeeks: 45,
    toWeeks: 78,
    area: 'motorik',
    goal: 'Erste Schritte mit stabilem Halt.',
    material: 'Ein leichter, standfester Kinderstuhl',
    steps: [
      'Stellt den Stuhl mit der Lehne zum Kind.',
      'Lasst es sich daran hochziehen und schieben.',
      'Sorgt für freie Fläche ohne Kanten.',
      'Rutschende Böden vorher absichern.',
    ],
    durationMin: 10,
  },
  {
    id: 'mo-bauklotz-einhand',
    title: 'Zwei Klötze halten',
    fromWeeks: 30,
    toWeeks: 78,
    area: 'motorik',
    goal: 'Beidhändiges Greifen und Zusammenführen.',
    material: 'Zwei kleine Bausteine',
    steps: [
      'Gebt eurem Kind einen Stein in jede Hand.',
      'Zeigt, wie ihr sie aneinanderschlagt.',
      'Wartet, ob es die Bewegung übernimmt.',
      'Lobt jedes Zusammenführen.',
    ],
    durationMin: 8,
  },
  {
    id: 'mo-rutschen',
    title: 'Die kleine Rutsche',
    fromWeeks: 70,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Mut, Gleichgewicht und Körperkontrolle.',
    material: 'Eine niedrige Kinderrutsche',
    steps: [
      'Begleitet euer Kind beim ersten Mal die ganze Rutsche hinunter.',
      'Steht danach am Ende und fangt es auf.',
      'Zieht euch zurück, sobald es sicher wirkt.',
      'Bleibt bei der Leiter in Griffweite.',
    ],
    durationMin: 15,
  },
  {
    id: 'mo-ball-werfen-ziel',
    title: 'Ball in den Korb',
    fromWeeks: 90,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Zielgenauigkeit und Auge-Hand-Koordination.',
    material: 'Ein Wäschekorb, weiche Bälle',
    steps: [
      'Stellt den Korb einen Meter entfernt auf.',
      'Werft selbst einmal hinein.',
      'Lasst euer Kind werfen, verkürzt notfalls die Distanz.',
      'Zählt die Treffer gemeinsam.',
    ],
    durationMin: 12,
  },
  {
    id: 'mo-kriechen-unter',
    title: 'Unter dem Tisch durch',
    fromWeeks: 45,
    toWeeks: 130,
    area: 'motorik',
    goal: 'Räumliche Einschätzung und Bewegungsplanung.',
    material: 'Ein Tisch mit Decke',
    steps: [
      'Legt eine Decke über den Tisch, sodass eine Höhle entsteht.',
      'Krabbelt einmal selbst hindurch.',
      'Legt ein Spielzeug hinein.',
      'Lasst euer Kind die Höhle selbst gestalten.',
    ],
    durationMin: 15,
  },
  {
    id: 'mo-zehenspitzen',
    title: 'Auf Zehenspitzen',
    fromWeeks: 100,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Wadenmuskulatur und Gleichgewicht.',
    material: 'Ein hoch gehängtes Spielzeug',
    steps: [
      'Hängt etwas knapp außer Reichweite auf.',
      'Zeigt, wie ihr euch streckt.',
      'Lasst euer Kind versuchen, es zu erreichen.',
      'Senkt es, wenn der Frust überwiegt.',
    ],
    durationMin: 8,
  },
  {
    id: 'mo-krabbeln-rueckwaerts',
    title: 'Rückwärts krabbeln',
    fromWeeks: 30,
    toWeeks: 60,
    area: 'motorik',
    goal: 'Bewegungsrichtung bewusst steuern.',
    material: 'Ein Spielzeug',
    steps: [
      'Legt das Spielzeug hinter euer Kind.',
      'Lockt es, sich rückwärts zu bewegen.',
      'Helft an den Füßen, wenn es feststeckt.',
      'Kurze Einheiten, es ist anstrengend.',
    ],
    durationMin: 6,
  },
  {
    id: 'mo-waescheklammern',
    title: 'Wäscheklammern anstecken',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Kraft in Daumen und Zeigefinger aufbauen.',
    material: 'Weiche Wäscheklammern, ein Karton',
    steps: [
      'Zeigt, wie eine Klammer geöffnet wird.',
      'Lasst euer Kind sie an den Kartonrand stecken.',
      'Nehmt leichtgängige Klammern.',
      'Sortiert sie danach nach Farben.',
    ],
    durationMin: 12,
  },
  {
    id: 'mo-huepfen-beidbeinig',
    title: 'Mit beiden Füßen hüpfen',
    fromWeeks: 100,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Sprungkraft und Koordination.',
    material: 'Ein Kissen oder ein Klebestreifen am Boden',
    steps: [
      'Markiert eine Linie am Boden.',
      'Hüpft selbst darüber.',
      'Haltet anfangs beide Hände.',
      'Zählt die Sprünge laut mit.',
    ],
    durationMin: 8,
  },
  {
    id: 'mo-drehen-im-stand',
    title: 'Sich im Stand drehen',
    fromWeeks: 90,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Gleichgewicht bei Drehbewegungen.',
    material: 'Nichts',
    steps: [
      'Dreht euch gemeinsam langsam im Kreis.',
      'Bleibt stehen und wartet, bis der Schwindel vergeht.',
      'Wechselt die Richtung.',
      'Nur wenige Umdrehungen, dann Pause.',
    ],
    durationMin: 6,
  },
  {
    id: 'mo-fingerfarben-gross',
    title: 'Großflächig malen',
    fromWeeks: 80,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Ganzarmbewegung, Vorstufe der Schreibbewegung.',
    material: 'Großes Papier, Fingerfarbe',
    steps: [
      'Klebt ein großes Blatt an die Wand oder auf den Boden.',
      'Lasst euer Kind mit der ganzen Hand malen.',
      'Zeigt Kreise und große Bögen.',
      'Kleidung vorher ausziehen.',
    ],
    durationMin: 15,
  },
  {
    id: 'mo-tuecher-ziehen-hoch',
    title: 'Tuch aus der Hand ziehen',
    fromWeeks: 26,
    toWeeks: 60,
    area: 'motorik',
    goal: 'Zugkraft und Griffstärke.',
    material: 'Ein Stofftuch',
    steps: [
      'Haltet das Tuch fest und lasst euer Kind ziehen.',
      'Gebt langsam nach, damit es gewinnt.',
      'Wechselt die Hände.',
      'Ohne Ruck, kein Tauziehen.',
    ],
    durationMin: 5,
  },
  {
    id: 'mo-stufen-sitzend',
    title: 'Im Sitzen die Treppe hinunter',
    fromWeeks: 50,
    toWeeks: 110,
    area: 'motorik',
    goal: 'Sicheren Abstieg lernen.',
    material: 'Eine Treppe',
    steps: [
      'Setzt euer Kind auf die oberste Stufe.',
      'Zeigt, wie man sich Stufe für Stufe hinunterschiebt.',
      'Bleibt eine Stufe unterhalb.',
      'Übt es täglich, bis es sicher ist.',
    ],
    durationMin: 8,
  },
  {
    id: 'mo-tragen-helfen',
    title: 'Etwas tragen',
    fromWeeks: 70,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Kraft, Gleichgewicht und Selbstwirksamkeit.',
    material: 'Ein leichter Korb',
    steps: [
      'Gebt eurem Kind einen leichten Gegenstand zum Tragen.',
      'Bittet es, ihn in ein anderes Zimmer zu bringen.',
      'Bedankt euch für die Hilfe.',
      'Steigert das Gewicht langsam.',
    ],
    durationMin: 6,
  },
  {
    id: 'mo-schaukelbrett',
    title: 'Auf dem Balancebrett',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Gleichgewicht auf instabilem Untergrund.',
    material: 'Ein Balancebrett oder ein fest gerolltes Handtuch',
    steps: [
      'Haltet beide Hände eures Kindes.',
      'Lasst es sich langsam von einer Seite zur anderen wiegen.',
      'Reduziert die Hilfe auf eine Hand.',
      'Weichen Untergrund darunter legen.',
    ],
    durationMin: 8,
  },
  {
    id: 'mo-pinzette-loeffel',
    title: 'Mit dem Löffel umfüllen',
    fromWeeks: 100,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Präzision und Ausdauer.',
    material: 'Zwei Schüsseln, große Bohnen, ein Löffel',
    steps: [
      'Füllt eine Schüssel, die andere bleibt leer.',
      'Zeigt einmal das Umlöffeln.',
      'Lasst euer Kind fortfahren.',
      'Nur unter Aufsicht.',
    ],
    durationMin: 12,
  },
]
