import type { Exercise } from './types'

/** Übungen für die ersten drei Monate (Woche 0 bis 12). */
export const NEWBORN_EXERCISES: Exercise[] = [
  {
    id: 'nb-blickkontakt',
    title: 'Blick halten',
    fromWeeks: 0,
    toWeeks: 12,
    area: 'sozial',
    goal: 'Bindung stärken und die Augenmuskulatur üben.',
    material: 'Nichts',
    steps: [
      'Haltet euer Kind so, dass euer Gesicht etwa 25 Zentimeter entfernt ist.',
      'Wartet, bis es euch anschaut, und haltet den Blick.',
      'Sprecht ruhig weiter, ohne das Gesicht zu bewegen.',
      'Beendet, sobald euer Kind wegschaut – das ist die Pausenbitte.',
    ],
    durationMin: 3,
  },
  {
    id: 'nb-bauchlage-brust',
    title: 'Bauchlage auf der Brust',
    fromWeeks: 0,
    toWeeks: 10,
    area: 'motorik',
    goal: 'Nacken- und Schultermuskulatur stärken, ohne dass es sich nach Übung anfühlt.',
    material: 'Nichts',
    steps: [
      'Legt euch halb aufrecht hin, euer Kind bäuchlings auf eure Brust.',
      'Sprecht mit ihm, damit es den Kopf zu eurer Stimme hebt.',
      'Bleibt zwei bis drei Minuten, mehrmals am Tag.',
      'Hört auf, sobald es quengelt – Frust hilft der Muskulatur nicht.',
    ],
    durationMin: 5,
  },
  {
    id: 'nb-kontrastkarten',
    title: 'Schwarz-Weiß-Muster',
    fromWeeks: 2,
    toWeeks: 12,
    area: 'sinne',
    goal: 'Die noch schwache Sehschärfe mit starken Kontrasten anregen.',
    material: 'Ein Blatt Papier mit dicken schwarzen Streifen oder Kreisen',
    steps: [
      'Haltet das Muster etwa 25 Zentimeter vor das Gesicht.',
      'Wartet, bis euer Kind es fixiert.',
      'Bewegt es ganz langsam zur Seite und beobachtet, ob der Blick folgt.',
      'Wechselt nach ein paar Tagen das Muster.',
    ],
    durationMin: 3,
  },
  {
    id: 'nb-stimme-orten',
    title: 'Stimme orten',
    fromWeeks: 1,
    toWeeks: 12,
    area: 'sinne',
    goal: 'Hören und Kopfdrehung koppeln.',
    material: 'Nichts',
    steps: [
      'Legt euer Kind auf den Rücken.',
      'Sprecht leise von der einen Seite, dann von der anderen.',
      'Gebt ihm Zeit – die Drehung dauert am Anfang mehrere Sekunden.',
      'Belohnt jede Reaktion mit einem Lächeln und weiterem Sprechen.',
    ],
    durationMin: 3,
  },
  {
    id: 'nb-haut-auf-haut',
    title: 'Haut auf Haut',
    fromWeeks: 0,
    toWeeks: 8,
    area: 'sozial',
    goal: 'Kreislauf, Temperatur und Atmung regulieren, Bindung aufbauen.',
    material: 'Eine Decke',
    steps: [
      'Legt euer Kind nur mit Windel auf eure nackte Brust.',
      'Deckt euch beide gemeinsam zu.',
      'Bleibt mindestens zwanzig Minuten ruhig liegen.',
      'Das funktioniert bei beiden Elternteilen gleich gut.',
    ],
    durationMin: 30,
  },
  {
    id: 'nb-finger-greifen',
    title: 'Finger greifen lassen',
    fromWeeks: 0,
    toWeeks: 10,
    area: 'motorik',
    goal: 'Den Greifreflex nutzen und die Handmuskulatur aktivieren.',
    material: 'Nichts',
    steps: [
      'Legt euren Finger in die Handfläche eures Kindes.',
      'Es schließt die Faust automatisch – lasst es festhalten.',
      'Zieht sanft, sodass es leichten Widerstand spürt.',
      'Wechselt zwischen beiden Händen.',
    ],
    durationMin: 3,
  },
  {
    id: 'nb-massage-beine',
    title: 'Beinmassage',
    fromWeeks: 2,
    toWeeks: 26,
    area: 'sinne',
    goal: 'Körperwahrnehmung fördern und Blähungen lindern.',
    material: 'Etwas Öl, zum Beispiel Mandelöl',
    steps: [
      'Wärmt das Öl in den Händen an.',
      'Streicht mit leichtem Druck vom Fuß zur Hüfte, jedes Bein einzeln.',
      'Radelt danach die Beine langsam durch.',
      'Beobachtet die Reaktion – bei Abwehr abbrechen.',
    ],
    durationMin: 8,
  },
  {
    id: 'nb-tragen-wechseln',
    title: 'Trageseite wechseln',
    fromWeeks: 0,
    toWeeks: 26,
    area: 'motorik',
    goal: 'Einseitige Belastung und Kopfvorzugshaltung vermeiden.',
    material: 'Nichts',
    steps: [
      'Merkt euch, auf welcher Seite ihr üblicherweise tragt.',
      'Wechselt bei jedem zweiten Tragen bewusst die Seite.',
      'Legt euer Kind auch im Bett abwechselnd anders herum.',
      'Achtet darauf, ob es eine Seite deutlich bevorzugt.',
    ],
    durationMin: 1,
  },
  {
    id: 'nb-nachahmen-mund',
    title: 'Zunge zeigen',
    fromWeeks: 1,
    toWeeks: 12,
    area: 'sozial',
    goal: 'Die frühe Nachahmungsfähigkeit anregen.',
    material: 'Nichts',
    steps: [
      'Haltet euer Gesicht dicht vor das eures Kindes.',
      'Streckt langsam die Zunge heraus und zieht sie wieder ein.',
      'Wiederholt es drei- bis viermal mit Pausen dazwischen.',
      'Wartet geduldig – die Antwort kann bis zu einer Minute dauern.',
    ],
    durationMin: 3,
  },
  {
    id: 'nb-singen',
    title: 'Immer dasselbe Lied',
    fromWeeks: 0,
    toWeeks: 52,
    area: 'sprache',
    goal: 'Sprachmelodie und Vertrautheit über Wiederholung aufbauen.',
    material: 'Nichts',
    steps: [
      'Wählt ein Lied, das ihr beide gerne singt.',
      'Singt es immer in derselben Situation, etwa beim Wickeln.',
      'Nutzt Pausen, in denen euer Kind reagieren kann.',
      'Bleibt monatelang beim selben Lied – die Wiederholung ist der Punkt.',
    ],
    durationMin: 3,
  },
  {
    id: 'nb-pucken-alternativ',
    title: 'Hände zur Mitte führen',
    fromWeeks: 2,
    toWeeks: 16,
    area: 'motorik',
    goal: 'Die Körpermitte erfahrbar machen, Grundlage für koordiniertes Greifen.',
    material: 'Nichts',
    steps: [
      'Legt euer Kind auf den Rücken.',
      'Führt seine beiden Hände sanft vor der Brust zusammen.',
      'Haltet sie kurz dort und lasst wieder los.',
      'Wiederholt es fünfmal, ohne Druck.',
    ],
    durationMin: 3,
  },
  {
    id: 'nb-spaziergang',
    title: 'Der tägliche Spaziergang',
    fromWeeks: 1,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Licht, Luft und Bewegung – gut für Schlafrhythmus und Stimmung, für beide.',
    material: 'Kinderwagen oder Trage',
    steps: [
      'Geht einmal täglich raus, unabhängig vom Wetter.',
      'Beschreibt unterwegs, was ihr seht, auch wenn es noch nicht verstanden wird.',
      'Haltet gelegentlich an und lasst euer Kind schauen.',
      'Zwanzig Minuten reichen völlig.',
    ],
    durationMin: 20,
  },
  {
    id: 'nb-rassel-verfolgen',
    title: 'Geräusch verfolgen',
    fromWeeks: 4,
    toWeeks: 16,
    area: 'sinne',
    goal: 'Hören und Sehen miteinander verknüpfen.',
    material: 'Eine leise Rassel oder ein Knisterpapier',
    steps: [
      'Macht das Geräusch seitlich neben dem Kopf, außerhalb des Blickfelds.',
      'Wartet, bis euer Kind den Kopf dreht.',
      'Zeigt ihm dann die Quelle.',
      'Wechselt die Seite.',
    ],
    durationMin: 4,
  },
  {
    id: 'nb-rollentraining',
    title: 'Sanft auf die Seite',
    fromWeeks: 6,
    toWeeks: 20,
    area: 'motorik',
    goal: 'Die Drehbewegung vorbereiten.',
    material: 'Eine feste Unterlage',
    steps: [
      'Legt euer Kind auf den Rücken.',
      'Führt ein Bein sanft über das andere, sodass sich die Hüfte dreht.',
      'Lasst los und schaut, ob es mitgeht.',
      'Wechselt die Richtung, jeweils drei Wiederholungen.',
    ],
    durationMin: 4,
  },
  {
    id: 'nb-fuesse-beruehren',
    title: 'Füße entdecken',
    fromWeeks: 8,
    toWeeks: 26,
    area: 'sinne',
    goal: 'Das Körperschema erweitern.',
    material: 'Nichts',
    steps: [
      'Führt die Hände eures Kindes zu seinen Füßen.',
      'Benennt dabei, was ihr berührt: Fuß, Zehen, Knie.',
      'Lasst los und schaut, ob es selbst dorthin greift.',
      'Ein Söckchen mit Geräusch macht es interessanter.',
    ],
    durationMin: 4,
  },
  {
    id: 'nb-mobile-erreichbar',
    title: 'Mobile in Reichweite',
    fromWeeks: 8,
    toWeeks: 20,
    area: 'motorik',
    goal: 'Vom Anschauen zum gezielten Treffen kommen.',
    material: 'Ein Mobile oder ein an einer Schnur befestigtes Tuch',
    steps: [
      'Hängt das Mobile so tief, dass euer Kind es mit ausgestrecktem Arm berührt.',
      'Zeigt einmal, wie es sich bewegt, wenn man es anstößt.',
      'Lasst euer Kind selbst probieren.',
      'Hängt es höher, sobald es zuverlässig trifft.',
    ],
    durationMin: 10,
  },
  {
    id: 'nb-wechselgespraech',
    title: 'Wechselgespräch',
    fromWeeks: 6,
    toWeeks: 52,
    area: 'sprache',
    goal: 'Den Rhythmus von Sprechen und Zuhören lernen.',
    material: 'Nichts',
    steps: [
      'Wartet, bis euer Kind einen Laut macht.',
      'Antwortet mit demselben Laut.',
      'Macht eine Pause und wartet auf die nächste Äußerung.',
      'Führt das Spiel weiter, solange euer Kind mitmacht.',
    ],
    durationMin: 5,
  },
  {
    id: 'nb-spiegel',
    title: 'Blick in den Spiegel',
    fromWeeks: 8,
    toWeeks: 78,
    area: 'sozial',
    goal: 'Gesichter erforschen und später sich selbst erkennen.',
    material: 'Ein bruchsicherer Spiegel',
    steps: [
      'Haltet euer Kind vor den Spiegel.',
      'Zeigt auf euer beider Spiegelbild und benennt: "Das ist Mama, das bist du."',
      'Winkt, macht Grimassen und beobachtet die Reaktion.',
      'Wiederholt es regelmäßig – die Reaktion ändert sich über die Monate.',
    ],
    durationMin: 5,
  },
  {
    id: 'nb-tuch-textur',
    title: 'Verschiedene Stoffe',
    fromWeeks: 4,
    toWeeks: 26,
    area: 'sinne',
    goal: 'Tastsinn differenzieren.',
    material: 'Drei Stoffe mit unterschiedlicher Oberfläche',
    steps: [
      'Streicht jeden Stoff langsam über Arm und Hand.',
      'Benennt, was ihr tut: "Das ist weich, das ist rau."',
      'Lasst euer Kind selbst greifen, wenn es kann.',
      'Beobachtet, welcher Stoff die meiste Reaktion auslöst.',
    ],
    durationMin: 5,
  },
  {
    id: 'nb-licht-schatten',
    title: 'Licht und Schatten',
    fromWeeks: 6,
    toWeeks: 26,
    area: 'sinne',
    goal: 'Kontraste und Bewegung wahrnehmen.',
    material: 'Ein Fenster mit Vorhang oder Blätter im Wind',
    steps: [
      'Setzt euch mit eurem Kind so, dass es die bewegten Schatten sieht.',
      'Beschreibt, was passiert.',
      'Lasst es einige Minuten schauen, ohne dazwischenzureden.',
      'Beendet, wenn der Blick abschweift.',
    ],
    durationMin: 5,
  },
  {
    id: 'nb-arme-strecken',
    title: 'Arme öffnen und schließen',
    fromWeeks: 3,
    toWeeks: 20,
    area: 'motorik',
    goal: 'Schultergelenke mobilisieren und Körpergefühl aufbauen.',
    material: 'Nichts',
    steps: [
      'Nehmt die Hände eures Kindes in eure.',
      'Öffnet die Arme langsam zur Seite und führt sie wieder zusammen.',
      'Sprecht oder singt dazu im Rhythmus.',
      'Fünf Wiederholungen, dann Pause.',
    ],
    durationMin: 3,
  },
  {
    id: 'nb-wickelgespraech',
    title: 'Wickeln als Gespräch',
    fromWeeks: 0,
    toWeeks: 104,
    area: 'sprache',
    goal: 'Aus einer Pflichtsituation die verlässlichste Sprachzeit des Tages machen.',
    material: 'Nichts',
    steps: [
      'Kündigt jeden Schritt an: "Jetzt ziehe ich den Body aus."',
      'Macht Pausen, in denen euer Kind reagieren kann.',
      'Benennt Körperteile, während ihr sie berührt.',
      'Zieht das Wickeln nicht künstlich in die Länge, wenn es genug hat.',
    ],
    durationMin: 5,
  },
  {
    id: 'nb-schaukeln',
    title: 'Sanftes Schaukeln',
    fromWeeks: 0,
    toWeeks: 26,
    area: 'sinne',
    goal: 'Gleichgewichtssinn anregen und beruhigen.',
    material: 'Nichts',
    steps: [
      'Nehmt euer Kind auf den Arm, den Kopf gestützt.',
      'Schaukelt langsam seitwärts, im Takt eures Atems.',
      'Summt leise dazu.',
      'Keine ruckartigen Bewegungen, kein Hochwerfen.',
    ],
    durationMin: 5,
  },
  {
    id: 'nb-bauchlage-rolle',
    title: 'Bauchlage mit Rolle',
    fromWeeks: 6,
    toWeeks: 20,
    area: 'motorik',
    goal: 'Die Bauchlage erleichtern, wenn sie noch anstrengend ist.',
    material: 'Ein zusammengerolltes Handtuch',
    steps: [
      'Legt die Rolle unter die Brust eures Kindes, Arme davor.',
      'Legt ein interessantes Objekt in Blickrichtung.',
      'Bleibt daneben und sprecht mit ihm.',
      'Zwei bis drei Minuten, mehrmals täglich.',
    ],
    durationMin: 4,
  },
  {
    id: 'nb-namen-nutzen',
    title: 'Den Namen verwenden',
    fromWeeks: 0,
    toWeeks: 52,
    area: 'sprache',
    goal: 'Den eigenen Namen als Zeichen für sich selbst verankern.',
    material: 'Nichts',
    steps: [
      'Sprecht euer Kind bewusst mit dem Namen an, nicht nur mit Kosenamen.',
      'Nutzt ihn am Satzanfang, damit er betont ist.',
      'Wartet nach dem Namen kurz, bevor ihr weitersprecht.',
      'Beobachtet ab etwa fünf Monaten, ob eine Reaktion kommt.',
    ],
    durationMin: 1,
  },
  {
    id: 'nb-atemrhythmus',
    title: 'Gemeinsamer Atem',
    fromWeeks: 0,
    toWeeks: 12,
    area: 'sozial',
    goal: 'Ein unruhiges Kind über die eigene Ruhe beruhigen.',
    material: 'Nichts',
    steps: [
      'Legt euer weinendes Kind an eure Brust.',
      'Atmet bewusst langsam und tief.',
      'Sprecht nicht, summt höchstens.',
      'Gebt der Sache mehrere Minuten, bevor ihr etwas anderes probiert.',
    ],
    durationMin: 10,
  },
  {
    id: 'nb-hell-dunkel',
    title: 'Tag und Nacht unterscheidbar machen',
    fromWeeks: 0,
    toWeeks: 16,
    area: 'alltag',
    goal: 'Der inneren Uhr helfen, sich zu bilden.',
    material: 'Nichts',
    steps: [
      'Haltet es tagsüber hell und normal laut, auch beim Schlafen.',
      'Macht es nachts dunkel und leise, sprecht wenig.',
      'Wickelt und füttert nachts ohne großes Licht.',
      'Zieht es über Wochen konsequent durch.',
    ],
    durationMin: 1,
  },
  {
    id: 'nb-fingerspiel-einfach',
    title: 'Erstes Fingerspiel',
    fromWeeks: 8,
    toWeeks: 52,
    area: 'sprache',
    goal: 'Sprache mit Berührung und Erwartung verbinden.',
    material: 'Nichts',
    steps: [
      'Wählt einen kurzen Reim mit Berührung am Ende.',
      'Sprecht ihn langsam und immer gleich.',
      'Macht vor der Pointe eine Pause.',
      'Wiederholt ihn täglich – die Vorfreude entsteht erst durch Wiederholung.',
    ],
    durationMin: 3,
  },
  {
    id: 'nb-position-wechseln',
    title: 'Positionen wechseln',
    fromWeeks: 2,
    toWeeks: 26,
    area: 'motorik',
    goal: 'Einseitige Belastung vermeiden und verschiedene Perspektiven bieten.',
    material: 'Eine Decke auf dem Boden',
    steps: [
      'Wechselt alle zwanzig bis dreißig Minuten die Position: Rücken, Bauch, Seite, Arm.',
      'Legt euer Kind so, dass es mal zum Fenster, mal ins Zimmer schaut.',
      'Vermeidet lange Zeit in Wippe oder Autositz.',
      'Auf dem Boden lernt es mehr als in jeder Sitzschale.',
    ],
    durationMin: 1,
  },
]
