import type { Exercise } from './types'

/** Übungen für das dritte Lebensjahr (Woche 104 bis 156). */
export const PRESCHOOL_EXERCISES: Exercise[] = [
  {
    id: 'ps-schere',
    title: 'Erstes Schneiden',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Beidhändige Koordination und Feinmotorik.',
    material: 'Kinderschere mit abgerundeter Spitze, Papierstreifen',
    steps: [
      'Schneidet schmale Streifen vor, die mit einem Schnitt durchtrennt werden.',
      'Zeigt die Handhaltung: Daumen oben.',
      'Haltet das Papier anfangs selbst fest.',
      'Nur unter Aufsicht, Schere danach wegräumen.',
    ],
    durationMin: 12,
  },
  {
    id: 'ps-faedeln',
    title: 'Perlen auffädeln',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Auge-Hand-Koordination und Ausdauer.',
    material: 'Große Holzperlen, eine dicke Schnur mit festem Ende',
    steps: [
      'Verknotet eine Perle am Ende, damit nichts herunterrutscht.',
      'Fädelt eine Perle vor.',
      'Lasst euer Kind weitermachen.',
      'Nur große Perlen verwenden und dabeibleiben.',
    ],
    durationMin: 15,
  },
  {
    id: 'ps-balancieren',
    title: 'Auf der Linie balancieren',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Gleichgewicht und Körperbeherrschung.',
    material: 'Kreide oder Klebeband',
    steps: [
      'Zeichnet eine gerade Linie auf den Boden.',
      'Geht sie einmal vor.',
      'Haltet anfangs eine Hand.',
      'Macht später eine Kurve oder einen Zickzack daraus.',
    ],
    durationMin: 10,
  },
  {
    id: 'ps-einbein',
    title: 'Auf einem Bein stehen',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Gleichgewicht und Standfestigkeit.',
    material: 'Nichts',
    steps: [
      'Steht euch gegenüber und hebt ein Bein an.',
      'Zählt gemeinsam laut mit.',
      'Haltet euch anfangs an den Händen.',
      'Wechselt das Bein.',
    ],
    durationMin: 6,
  },
  {
    id: 'ps-memory-vier',
    title: 'Memory mit vier Paaren',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Gedächtnis und Abwarten üben.',
    material: 'Vier Kartenpaare mit klaren Motiven',
    steps: [
      'Legt die acht Karten offen hin und benennt alle Motive.',
      'Dreht sie um und spielt gemeinsam.',
      'Beginnt mit vier Paaren, mehr überfordert.',
      'Lasst euer Kind auch mal gewinnen, ohne es offensichtlich zu machen.',
    ],
    durationMin: 12,
  },
  {
    id: 'ps-zaehlen-alltag',
    title: 'Alles zählen',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Zahlen mit Mengen verknüpfen.',
    material: 'Nichts',
    steps: [
      'Zählt beim Treppensteigen die Stufen.',
      'Zählt Teller beim Tischdecken.',
      'Zeigt beim Zählen auf jedes Objekt einzeln.',
      'Bleibt bei kleinen Mengen bis fünf.',
    ],
    durationMin: 5,
  },
  {
    id: 'ps-geschichte-erfinden',
    title: 'Geschichte weitererzählen',
    fromWeeks: 130,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Fantasie und zusammenhängendes Erzählen.',
    material: 'Nichts',
    steps: [
      'Beginnt eine kurze Geschichte mit einer bekannten Figur.',
      'Haltet mitten im Satz an und fragt: "Und dann?"',
      'Nehmt jeden Vorschlag auf, egal wie unlogisch.',
      'Erzählt dieselbe Geschichte an anderen Tagen weiter.',
    ],
    durationMin: 10,
  },
  {
    id: 'ps-tisch-decken',
    title: 'Tisch decken',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Verantwortung übernehmen und zählen üben.',
    material: 'Unzerbrechliches Geschirr',
    steps: [
      'Gebt eurem Kind einen festen Teil der Aufgabe, etwa die Servietten.',
      'Zählt gemeinsam die Personen ab.',
      'Lasst Fehler stehen, korrigiert nicht sofort.',
      'Macht es zu einer täglichen Aufgabe.',
    ],
    durationMin: 8,
  },
  {
    id: 'ps-sortieren-groesse',
    title: 'Der Größe nach',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Reihenfolgen bilden und Größen miteinander vergleichen.',
    material: 'Drei bis fünf Gegenstände unterschiedlicher Größe',
    steps: [
      'Legt drei Gegenstände hin und ordnet sie gemeinsam.',
      'Benennt: klein, größer, am größten.',
      'Mischt und lasst euer Kind ordnen.',
      'Erweitert auf fünf, wenn drei sicher klappen.',
    ],
    durationMin: 10,
  },
  {
    id: 'ps-rollenspiel-arzt',
    title: 'Arzt spielen',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Ängste vor Untersuchungen abbauen.',
    material: 'Ein Stofftier, ein Pflaster, ein Löffel als Spatel',
    steps: [
      'Untersucht gemeinsam das Stofftier.',
      'Benennt jeden Schritt so, wie es die Ärztin tut.',
      'Lasst euer Kind die Rolle der Ärztin übernehmen.',
      'Spielt es vor dem nächsten echten Termin.',
    ],
    durationMin: 15,
  },
  {
    id: 'ps-backen',
    title: 'Gemeinsam backen',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Feinmotorik, Mengen und Geduld in einer Aktivität.',
    material: 'Ein einfaches Rezept, Schüssel, Löffel',
    steps: [
      'Wählt ein Rezept ohne rohes Ei zum Naschen.',
      'Gebt eurem Kind das Abmessen und Rühren.',
      'Benennt die Zutaten und die Mengen.',
      'Lasst es beim Ausstechen selbst entscheiden.',
    ],
    durationMin: 30,
  },
  {
    id: 'ps-gegensaetze',
    title: 'Gegensätze finden',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Begriffe schärfen und Wortschatz erweitern.',
    material: 'Nichts',
    steps: [
      'Nennt ein Wort: groß.',
      'Fragt nach dem Gegenteil.',
      'Zeigt es, wenn möglich, mit dem Körper.',
      'Bleibt bei klaren Paaren: heiß und kalt, oben und unten.',
    ],
    durationMin: 6,
  },
  {
    id: 'ps-hindernis-drinnen',
    title: 'Bewegungsparcours drinnen',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Bewegungsdrang an Regentagen ausleben.',
    material: 'Kissen, Stühle, eine Decke, Klebeband',
    steps: [
      'Baut vier Stationen: kriechen, balancieren, springen, umrunden.',
      'Geht die Strecke einmal gemeinsam ab.',
      'Lasst euer Kind die Reihenfolge bestimmen.',
      'Ändert eine Station jedes Mal.',
    ],
    durationMin: 20,
  },
  {
    id: 'ps-emotionen-bilder',
    title: 'Gesichter lesen',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Gefühle bei anderen erkennen und benennen.',
    material: 'Ein Buch mit Gesichtern oder ein Spiegel',
    steps: [
      'Macht ein Gefühl im Gesicht vor: fröhlich, traurig, wütend.',
      'Fragt, was das sein könnte.',
      'Lasst euer Kind es nachmachen.',
      'Verknüpft es mit erlebten Situationen.',
    ],
    durationMin: 8,
  },
  {
    id: 'ps-laufrad',
    title: 'Laufrad üben',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Gleichgewicht und Koordination für das spätere Radfahren.',
    material: 'Ein Laufrad in passender Höhe, Helm',
    steps: [
      'Stellt den Sattel so ein, dass beide Füße flach stehen.',
      'Lasst euer Kind erst nur gehend schieben.',
      'Rollen und Abstoßen kommen von selbst.',
      'Helm von Anfang an, ohne Diskussion.',
    ],
    durationMin: 20,
  },
  {
    id: 'ps-sortieren-waesche',
    title: 'Wäsche sortieren',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Kategorien bilden und im Haushalt mithelfen.',
    material: 'Saubere Wäsche',
    steps: [
      'Gebt eurem Kind einen Stapel Socken.',
      'Lasst es Paare suchen.',
      'Sortiert danach nach Personen.',
      'Lobt das Mitmachen, nicht die Genauigkeit.',
    ],
    durationMin: 12,
  },
  {
    id: 'ps-reim-erkennen',
    title: 'Reime finden',
    fromWeeks: 130,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Sprachbewusstsein aufbauen – eine Vorstufe des Lesens.',
    material: 'Nichts',
    steps: [
      'Sprecht einen bekannten Reim und lasst das letzte Wort weg.',
      'Wartet, ob euer Kind es ergänzt.',
      'Erfindet danach eigene Unsinnsreime.',
      'Lacht über die falschen – das ist der Punkt.',
    ],
    durationMin: 8,
  },
  {
    id: 'ps-pflanze-giessen',
    title: 'Eine eigene Pflanze',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Verantwortung und Geduld über Wochen erleben.',
    material: 'Ein Topf, Erde, schnell keimende Samen wie Kresse',
    steps: [
      'Füllt gemeinsam den Topf und sät die Samen.',
      'Stellt ihn an einen Platz, den euer Kind erreicht.',
      'Gießt jeden Tag zur selben Zeit gemeinsam.',
      'Beobachtet und beschreibt die Veränderung.',
    ],
    durationMin: 8,
  },
  {
    id: 'ps-wuerfelspiel',
    title: 'Erstes Würfelspiel',
    fromWeeks: 130,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Regeln einhalten und abwechseln lernen.',
    material: 'Ein Würfel mit Punkten, ein einfaches Brettspiel',
    steps: [
      'Erklärt die Regel in einem Satz.',
      'Würfelt abwechselnd und zählt die Felder gemeinsam ab.',
      'Bleibt bei kurzen Spielen von fünf Minuten.',
      'Sprecht über das Verlieren, bevor es passiert.',
    ],
    durationMin: 10,
  },
  {
    id: 'ps-nachbauen',
    title: 'Bauwerk nachbauen',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Räumliches Denken und genaues Hinschauen.',
    material: 'Zwei gleiche Sets aus je vier Bausteinen',
    steps: [
      'Baut etwas Einfaches aus drei Steinen.',
      'Gebt eurem Kind dieselben Steine.',
      'Lasst es nachbauen, ohne zu korrigieren.',
      'Tauscht die Rollen: Euer Kind baut vor.',
    ],
    durationMin: 12,
  },
  {
    id: 'ps-schatzsuche',
    title: 'Kleine Schatzsuche',
    fromWeeks: 130,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Anweisungen verstehen und Ausdauer üben.',
    material: 'Drei versteckte Gegenstände',
    steps: [
      'Versteckt drei Dinge in einem Zimmer.',
      'Gebt Hinweise mit Ortsangaben: unter, hinter, neben.',
      'Lasst euer Kind suchen, ohne zu verraten.',
      'Feiert jeden Fund.',
    ],
    durationMin: 12,
  },
  {
    id: 'ps-selbst-eingiessen',
    title: 'Selbst eingießen',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Selbstständigkeit bei Tisch.',
    material: 'Ein kleiner Krug, ein Becher',
    steps: [
      'Füllt den Krug nur zu einem Drittel.',
      'Zeigt langsam vor, wie ihr gießt.',
      'Legt ein Tuch bereit und sagt nichts, wenn etwas danebengeht.',
      'Lasst euer Kind selbst aufwischen.',
    ],
    durationMin: 6,
  },
  {
    id: 'ps-blaetter-sammeln',
    title: 'Naturschätze sammeln',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Genaues Beobachten und Sortieren.',
    material: 'Ein Beutel oder Korb',
    steps: [
      'Sammelt beim Spaziergang Blätter, Steine und Zapfen.',
      'Sortiert sie zu Hause nach Farbe oder Größe.',
      'Benennt, was ihr gefunden habt.',
      'Klebt die schönsten auf ein Blatt Papier.',
    ],
    durationMin: 25,
  },
  {
    id: 'ps-stille-uebung',
    title: 'Eine Minute Stille',
    fromWeeks: 130,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Zur Ruhe kommen und bewusst hören.',
    material: 'Nichts',
    steps: [
      'Setzt euch gemeinsam hin und schließt die Augen.',
      'Seid eine Minute lang still.',
      'Sammelt danach, welche Geräusche ihr gehört habt.',
      'Steigert die Zeit nur langsam.',
    ],
    durationMin: 5,
  },
  {
    id: 'ps-post-selber',
    title: 'Einen Brief malen',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Beziehungen pflegen und Bedeutung von Schrift erahnen.',
    material: 'Papier, Stifte, ein Kuvert',
    steps: [
      'Lasst euer Kind ein Bild für die Großeltern malen.',
      'Schreibt dazu, was es erzählt.',
      'Steckt es gemeinsam ins Kuvert.',
      'Werft es zusammen in den Briefkasten.',
    ],
    durationMin: 20,
  },
  {
    id: 'ps-zaehne-selbst',
    title: 'Zähne selbst putzen',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Selbstständigkeit aufbauen, ohne die Gründlichkeit zu verlieren.',
    material: 'Kinderzahnbürste, fluoridhaltige Kinderzahnpasta',
    steps: [
      'Lasst euer Kind zuerst selbst putzen.',
      'Putzt danach gründlich nach – das bleibt bis ins Schulalter nötig.',
      'Nutzt ein Lied oder eine Sanduhr für die Dauer.',
      'Immer zweimal täglich, ohne Verhandlung.',
    ],
    durationMin: 5,
  },
  {
    id: 'ps-was-passiert-dann',
    title: 'Was passiert dann?',
    fromWeeks: 130,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Abläufe vorhersehen und in Reihenfolge denken.',
    material: 'Nichts',
    steps: [
      'Beschreibt den Anfang einer bekannten Handlung.',
      'Fragt, was als Nächstes kommt.',
      'Lasst euer Kind den ganzen Ablauf erzählen.',
      'Nutzt Abläufe aus dem eigenen Alltag.',
    ],
    durationMin: 8,
  },
  {
    id: 'ps-freund-besuch',
    title: 'Besuch von einem anderen Kind',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Gemeinsames Spiel und Konfliktlösung üben.',
    material: 'Ausreichend Spielzeug, doppelt vorhanden',
    steps: [
      'Räumt die Lieblingssachen vorher weg, um Konflikte zu vermeiden.',
      'Legt Material bereit, das nebeneinander bespielt werden kann.',
      'Bleibt in der Nähe und greift nur bei Bedarf ein.',
      'Haltet den Besuch kurz, eine Stunde reicht.',
    ],
    durationMin: 60,
  },
]
