import type { Exercise } from './types'

/** Übungen mit Schwerpunkt auf Wahrnehmung und Bewegung. */
export const SENSORY_EXERCISES: Exercise[] = [
  {
    id: 'se-duefte',
    title: 'Düfte kennenlernen',
    fromWeeks: 40,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Den Geruchssinn bewusst einsetzen.',
    material: 'Zimt, Orangenschale, frische Kräuter',
    steps: [
      'Haltet ein Gefäß in kurzem Abstand unter die Nase.',
      'Benennt den Geruch.',
      'Wechselt zwischen zwei bis drei Düften.',
      'Nichts direkt an die Nase halten, nichts Scharfes verwenden.',
    ],
    durationMin: 6,
  },
  {
    id: 'se-warm-kalt',
    title: 'Warm und kalt',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Temperaturunterschiede benennen lernen.',
    material: 'Zwei Schüsseln mit lauwarmem und kühlem Wasser',
    steps: [
      'Stellt beide Schüsseln nebeneinander.',
      'Taucht selbst die Hand hinein und benennt.',
      'Lasst euer Kind beide vergleichen.',
      'Kein heißes Wasser, nur lauwarm.',
    ],
    durationMin: 8,
  },
  {
    id: 'se-barfuss-parcours',
    title: 'Barfußpfad',
    fromWeeks: 70,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Fußwahrnehmung und Gleichgewicht.',
    material: 'Handtuch, Teppich, Karton, ein Tablett mit Reis',
    steps: [
      'Legt drei bis vier Untergründe hintereinander.',
      'Geht die Strecke selbst barfuß vor.',
      'Haltet anfangs eine Hand.',
      'Benennt jeden Untergrund.',
    ],
    durationMin: 12,
  },
  {
    id: 'se-schaukel',
    title: 'Schaukeln am Spielplatz',
    fromWeeks: 40,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Gleichgewichtssinn und Raumorientierung.',
    material: 'Eine Babyschaukel',
    steps: [
      'Setzt euer Kind sicher in die Schaukel.',
      'Schaukelt zunächst nur leicht.',
      'Beobachtet die Reaktion – manche Kinder mögen es nicht.',
      'Fünf Minuten reichen, danach Pause.',
    ],
    durationMin: 8,
  },
  {
    id: 'se-lichtspiel',
    title: 'Taschenlampe im dunklen Raum',
    fromWeeks: 70,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Licht und Schatten erforschen, Angst vor Dunkelheit abbauen.',
    material: 'Eine Taschenlampe',
    steps: [
      'Verdunkelt einen Raum leicht.',
      'Leuchtet an die Decke und lasst den Punkt wandern.',
      'Gebt eurem Kind die Lampe.',
      'Macht Schattenfiguren mit den Händen.',
    ],
    durationMin: 10,
  },
  {
    id: 'se-geraeusche-raten',
    title: 'Was war das für ein Geräusch?',
    fromWeeks: 90,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Genaues Hören und Zuordnen.',
    material: 'Alltagsgegenstände',
    steps: [
      'Erzeugt ein Geräusch hinter eurem Rücken, etwa Papier knüllen.',
      'Fragt, was das war.',
      'Zeigt danach die Lösung.',
      'Nehmt drei bis vier bekannte Geräusche.',
    ],
    durationMin: 8,
  },
  {
    id: 'se-schmecken-blind',
    title: 'Schmecken mit geschlossenen Augen',
    fromWeeks: 120,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Geschmack bewusst wahrnehmen.',
    material: 'Zwei bis drei bekannte Lebensmittel',
    steps: [
      'Nehmt nur Dinge, die euer Kind kennt und mag.',
      'Lasst es die Augen schließen.',
      'Gebt ein kleines Stück und fragt, was es war.',
      'Bei Ablehnung sofort abbrechen.',
    ],
    durationMin: 8,
  },
  {
    id: 'se-rollen-decke',
    title: 'In der Decke rollen',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Tiefenwahrnehmung durch sanften Druck.',
    material: 'Eine Decke',
    steps: [
      'Legt euer Kind an den Rand der ausgebreiteten Decke.',
      'Rollt es langsam ein, Kopf bleibt frei.',
      'Drückt sanft von außen und benennt die Körperteile.',
      'Rollt es wieder aus, wenn es genug hat.',
    ],
    durationMin: 8,
  },
  {
    id: 'se-hüpfen-matratze',
    title: 'Auf der Matratze hüpfen',
    fromWeeks: 90,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Sprungkraft und Gleichgewicht.',
    material: 'Eine Matratze auf dem Boden',
    steps: [
      'Legt die Matratze frei auf den Boden, nichts Hartes daneben.',
      'Haltet anfangs beide Hände.',
      'Zählt die Sprünge laut mit.',
      'Nie auf dem Bett mit Kante.',
    ],
    durationMin: 10,
  },
  {
    id: 'se-schnee-eis',
    title: 'Schnee oder Eiswürfel',
    fromWeeks: 80,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Zustandsveränderungen beobachten.',
    material: 'Eiswürfel oder Schnee, eine Schüssel',
    steps: [
      'Legt Eis in eine Schüssel auf den Tisch.',
      'Lasst euer Kind anfassen, kurz und mit Pausen.',
      'Beobachtet gemeinsam das Schmelzen.',
      'Benennt: kalt, nass, verschwunden.',
    ],
    durationMin: 12,
  },
  {
    id: 'se-krabbeln-untergrund',
    title: 'Verschiedene Untergründe',
    fromWeeks: 30,
    toWeeks: 78,
    area: 'motorik',
    goal: 'Anpassungsfähigkeit der Bewegung fördern.',
    material: 'Teppich, Fliesen, Decke, Gras',
    steps: [
      'Lasst euer Kind auf unterschiedlichen Böden krabbeln.',
      'Beobachtet, wie sich die Bewegung anpasst.',
      'Benennt: weich, hart, kitzelig.',
      'Draußen auf Sauberkeit achten.',
    ],
    durationMin: 12,
  },
  {
    id: 'se-farbe-suchen',
    title: 'Alles in einer Farbe',
    fromWeeks: 100,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Farben erkennen und Kategorien bilden.',
    material: 'Nichts',
    steps: [
      'Wählt eine Farbe für den Tag.',
      'Sucht gemeinsam Dinge in dieser Farbe.',
      'Sammelt sie an einem Platz.',
      'Zählt am Ende, wie viele es waren.',
    ],
    durationMin: 12,
  },
  {
    id: 'se-vibration',
    title: 'Töne spüren',
    fromWeeks: 30,
    toWeeks: 104,
    area: 'sinne',
    goal: 'Klang nicht nur hören, sondern fühlen.',
    material: 'Eine Trommel oder ein Karton',
    steps: [
      'Legt die Hand eures Kindes auf die Trommel.',
      'Klopft leicht, sodass es die Schwingung spürt.',
      'Wechselt zwischen laut und leise.',
      'Lasst euer Kind selbst klopfen.',
    ],
    durationMin: 8,
  },
  {
    id: 'se-nacht-himmel',
    title: 'In den Himmel schauen',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Ruhe finden und gemeinsam beobachten.',
    material: 'Eine Decke',
    steps: [
      'Legt euch gemeinsam auf den Rücken, drinnen oder draußen.',
      'Schaut nach oben und beschreibt, was ihr seht.',
      'Bleibt einige Minuten still.',
      'Macht es zu einer Gewohnheit an ruhigen Abenden.',
    ],
    durationMin: 10,
  },
  {
    id: 'se-massage-abend',
    title: 'Abendmassage',
    fromWeeks: 4,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Zur Ruhe kommen und Körperwahrnehmung stärken.',
    material: 'Etwas Öl',
    steps: [
      'Nehmt euch nach dem Bad fünf Minuten Zeit.',
      'Streicht mit ruhigem, gleichmäßigem Druck über Arme und Beine.',
      'Benennt die Körperteile leise.',
      'Beendet, sobald euer Kind unruhig wird.',
    ],
    durationMin: 8,
  },
  {
    id: 'se-wind-blaetter',
    title: 'Wind spüren',
    fromWeeks: 20,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Unsichtbare Phänomene erfahrbar machen.',
    material: 'Ein Tuch oder Blätter',
    steps: [
      'Geht an einem windigen Tag hinaus.',
      'Haltet ein leichtes Tuch hoch und lasst es flattern.',
      'Benennt, was der Wind macht.',
      'Beobachtet gemeinsam Blätter und Wolken.',
    ],
    durationMin: 12,
  },
  {
    id: 'se-tastsack',
    title: 'Fühlsack',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Gegenstände nur über den Tastsinn erkennen.',
    material: 'Ein Stoffbeutel, drei bekannte Gegenstände',
    steps: [
      'Zeigt die Gegenstände und benennt sie.',
      'Steckt sie in den Beutel.',
      'Lasst euer Kind hineingreifen und raten.',
      'Zeigt danach die Auflösung.',
    ],
    durationMin: 10,
  },
  {
    id: 'se-seifenblasen',
    title: 'Seifenblasen fangen',
    fromWeeks: 50,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Blickverfolgung und Auge-Hand-Koordination.',
    material: 'Seifenblasen',
    steps: [
      'Pustet Blasen in Richtung eures Kindes.',
      'Lasst es zuerst nur zuschauen.',
      'Ermuntert es später zum Zerplatzen mit dem Finger.',
      'Draußen machen, drinnen wird es rutschig.',
    ],
    durationMin: 12,
  },
  {
    id: 'se-schwer-leicht',
    title: 'Schwer und leicht',
    fromWeeks: 110,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Gewicht als Eigenschaft erfahren.',
    material: 'Zwei gleich große Behälter, einer gefüllt',
    steps: [
      'Gebt eurem Kind beide Behälter nacheinander in die Hand.',
      'Benennt: schwer und leicht.',
      'Lasst es sie mehrfach vergleichen.',
      'Füllt gemeinsam um und vergleicht erneut.',
    ],
    durationMin: 10,
  },
  {
    id: 'se-tanzen-stopp',
    title: 'Stopptanz',
    fromWeeks: 100,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Impulskontrolle und Körperbeherrschung.',
    material: 'Musik',
    steps: [
      'Tanzt gemeinsam zur Musik.',
      'Stoppt die Musik unvermittelt.',
      'Alle bleiben stehen wie eingefroren.',
      'Startet wieder, sobald alle still stehen.',
    ],
    durationMin: 10,
  },
]
