import type { Exercise } from './types'

/** Übungen für das zweite Lebensjahr (Woche 52 bis 104). */
export const TODDLER_EXERCISES: Exercise[] = [
  {
    id: 'td-schuetten-reis',
    title: 'Reis umfüllen',
    fromWeeks: 56,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Feinmotorik und Konzentration über Wiederholung.',
    material: 'Zwei Schüsseln, Reis oder Linsen, ein Tablett',
    steps: [
      'Stellt beides auf ein Tablett, das die Krümel auffängt.',
      'Zeigt einmal das Umfüllen mit einem Löffel.',
      'Lasst euer Kind selbst machen, ohne zu korrigieren.',
      'Nur unter Aufsicht – kleine Körner gehören nicht in Nase oder Ohr.',
    ],
    durationMin: 15,
  },
  {
    id: 'td-sortieren-farben',
    title: 'Nach Farben sortieren',
    fromWeeks: 78,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Kategorien bilden und Farben benennen.',
    material: 'Bausteine in zwei Farben, zwei Schüsseln',
    steps: [
      'Nehmt zunächst nur zwei klar unterschiedliche Farben.',
      'Sortiert die ersten Steine gemeinsam und benennt dabei laut.',
      'Lasst euer Kind weitermachen.',
      'Erweitert erst auf drei Farben, wenn zwei sicher klappen.',
    ],
    durationMin: 12,
  },
  {
    id: 'td-malen-stift',
    title: 'Kritzeln mit dickem Stift',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Die Vorstufe des Schreibens üben.',
    material: 'Dicke Wachsmalstifte, großes Papier',
    steps: [
      'Klebt das Papier auf den Tisch, damit es nicht verrutscht.',
      'Malt selbst ein paar Striche und Kreise.',
      'Lasst euer Kind machen, ohne Vorgaben.',
      'Hängt das Ergebnis auf und sprecht darüber.',
    ],
    durationMin: 12,
  },
  {
    id: 'td-tanzen',
    title: 'Musik und Tanzen',
    fromWeeks: 56,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Gleichgewicht, Rhythmus und gemeinsame Freude.',
    material: 'Musik',
    steps: [
      'Spielt Musik mit klarem Rhythmus.',
      'Bewegt euch selbst deutlich vor.',
      'Wechselt zwischen schnellen und langsamen Stücken.',
      'Baut Stopp-Momente ein: Musik aus, alle stehen still.',
    ],
    durationMin: 10,
  },
  {
    id: 'td-ball-treten',
    title: 'Ball treten',
    fromWeeks: 64,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Gleichgewicht auf einem Bein und Zielgenauigkeit.',
    material: 'Ein leichter Ball',
    steps: [
      'Legt den Ball direkt vor die Füße eures Kindes.',
      'Zeigt einmal, wie ihr ihn antippt.',
      'Lasst es probieren, anfangs mit Festhalten an eurer Hand.',
      'Stellt später ein Ziel auf.',
    ],
    durationMin: 10,
  },
  {
    id: 'td-puzzle-gross',
    title: 'Erstes Einlegepuzzle',
    fromWeeks: 60,
    toWeeks: 130,
    area: 'kognition',
    goal: 'Formen erkennen und zuordnen.',
    material: 'Ein Puzzle mit drei bis vier großen Teilen und Griffen',
    steps: [
      'Nehmt alle Teile heraus und legt sie daneben.',
      'Setzt eines gemeinsam ein und benennt das Motiv.',
      'Lasst euer Kind die restlichen probieren.',
      'Helft durch Drehen, nicht durch Einsetzen.',
    ],
    durationMin: 12,
  },
  {
    id: 'td-koerperteile',
    title: 'Wo ist deine Nase?',
    fromWeeks: 60,
    toWeeks: 130,
    area: 'sprache',
    goal: 'Körperteile benennen und zuordnen.',
    material: 'Nichts',
    steps: [
      'Fragt nach einem Körperteil und zeigt selbst darauf.',
      'Führt anfangs die Hand eures Kindes.',
      'Bleibt bei drei bis vier Körperteilen, bis sie sitzen.',
      'Baut es in Alltagssituationen ein, etwa beim Eincremen.',
    ],
    durationMin: 5,
  },
  {
    id: 'td-rollenspiel-puppe',
    title: 'Die Puppe füttern',
    fromWeeks: 64,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Eigene Erfahrungen im Spiel verarbeiten.',
    material: 'Eine Puppe oder ein Stofftier, ein Löffel',
    steps: [
      'Setzt die Puppe an den Tisch.',
      'Füttert sie einmal vor und sprecht dabei.',
      'Gebt eurem Kind den Löffel.',
      'Übernehmt die Rolle, die euch zugeteilt wird.',
    ],
    durationMin: 12,
  },
  {
    id: 'td-schuhe-holen',
    title: 'Kleine Aufträge',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Sprachverständnis und Selbstwirksamkeit stärken.',
    material: 'Nichts',
    steps: [
      'Gebt einen einfachen Auftrag: "Hol bitte deine Schuhe."',
      'Wartet ab, ohne zu wiederholen.',
      'Bedankt euch deutlich, wenn es klappt.',
      'Steigert später auf zwei Schritte.',
    ],
    durationMin: 3,
  },
  {
    id: 'td-wasserbahn',
    title: 'Wasser auf der Terrasse',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Materialerfahrung und Bewegungsfreude im Freien.',
    material: 'Eine Wanne mit Wasser, Becher, Löffel',
    steps: [
      'Stellt die Wanne flach befüllt auf den Boden.',
      'Gebt Gefäße in verschiedenen Größen dazu.',
      'Lasst euer Kind schöpfen und gießen.',
      'Nie unbeaufsichtigt – auch flaches Wasser ist gefährlich.',
    ],
    durationMin: 20,
  },
  {
    id: 'td-treppe-abwechselnd',
    title: 'Treppe Stufe für Stufe',
    fromWeeks: 70,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Sicheres Treppensteigen aufbauen.',
    material: 'Eine Treppe mit Geländer',
    steps: [
      'Geht neben eurem Kind, eine Hand am Geländer.',
      'Lasst es anfangs beide Füße auf jede Stufe setzen.',
      'Zählt die Stufen laut mit.',
      'Übt abwärts zuerst rückwärts oder im Sitzen.',
    ],
    durationMin: 8,
  },
  {
    id: 'td-buch-erzaehlen',
    title: 'Bilder erzählen',
    fromWeeks: 70,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Vom Benennen zum Erzählen kommen.',
    material: 'Ein Bilderbuch',
    steps: [
      'Lest nicht den Text, sondern beschreibt das Bild.',
      'Fragt: "Was macht der Hund?"',
      'Wartet die Antwort ab, auch wenn sie lange dauert.',
      'Nehmt die Antwort auf und erweitert sie um ein Wort.',
    ],
    durationMin: 10,
  },
  {
    id: 'td-haende-waschen',
    title: 'Hände waschen als Ritual',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Hygiene und Selbstständigkeit verbinden.',
    material: 'Ein Hocker am Waschbecken',
    steps: [
      'Stellt einen sicheren Tritt bereit.',
      'Zeigt die Reihenfolge: nass, Seife, reiben, spülen, abtrocknen.',
      'Singt dabei immer dasselbe kurze Lied.',
      'Lasst euer Kind so viel wie möglich selbst machen.',
    ],
    durationMin: 5,
  },
  {
    id: 'td-magnete-kuehlschrank',
    title: 'Magnete verschieben',
    fromWeeks: 60,
    toWeeks: 130,
    area: 'motorik',
    goal: 'Feinmotorik im Stehen üben.',
    material: 'Große Magnete, ein Kühlschrank',
    steps: [
      'Hängt mehrere große Magnete in Kinderhöhe.',
      'Zeigt, wie man sie verschiebt und abnimmt.',
      'Lasst euer Kind sie umordnen.',
      'Nur große Magnete – kleine sind bei Verschlucken gefährlich.',
    ],
    durationMin: 10,
  },
  {
    id: 'td-verstecken-koerper',
    title: 'Verstecken spielen',
    fromWeeks: 70,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Objektpermanenz und Spannung genießen.',
    material: 'Nichts',
    steps: [
      'Versteckt euch schlecht, mit sichtbaren Füßen.',
      'Ruft, damit euer Kind euch findet.',
      'Reagiert überrascht und freudig.',
      'Lasst euer Kind sich verstecken – auch wenn es die Augen zuhält.',
    ],
    durationMin: 10,
  },
  {
    id: 'td-knete',
    title: 'Kneten',
    fromWeeks: 70,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Handkraft und Materialerfahrung.',
    material: 'Selbst gemachte Knete aus Mehl, Salz, Öl und Wasser',
    steps: [
      'Mischt die Knete gemeinsam an.',
      'Zeigt Rollen, Drücken und Zupfen.',
      'Lasst euer Kind frei arbeiten, ohne Formvorgabe.',
      'Bleibt daneben, Salzteig schmeckt nicht, wird aber probiert.',
    ],
    durationMin: 15,
  },
  {
    id: 'td-gefuehle-benennen',
    title: 'Gefühle benennen',
    fromWeeks: 70,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Emotionen begreifbar und damit regulierbar machen.',
    material: 'Nichts',
    steps: [
      'Benennt, was ihr seht: "Du bist wütend, weil der Turm umgefallen ist."',
      'Wartet, ohne die Situation sofort zu lösen.',
      'Benennt auch eure eigenen Gefühle.',
      'Bietet danach Trost oder eine Lösung an.',
    ],
    durationMin: 3,
  },
  {
    id: 'td-anziehen-selbst',
    title: 'Selbst anziehen üben',
    fromWeeks: 78,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Selbstständigkeit im Alltag aufbauen.',
    material: 'Weite Kleidung',
    steps: [
      'Legt die Kleidung in der richtigen Reihenfolge bereit.',
      'Beginnt mit dem Einfachsten: Socken ausziehen, Mütze aufsetzen.',
      'Plant deutlich mehr Zeit ein.',
      'Greift erst ein, wenn euer Kind aufgibt.',
    ],
    durationMin: 10,
  },
  {
    id: 'td-tiere-nachmachen',
    title: 'Wie geht der Hund?',
    fromWeeks: 70,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Grobmotorik und Fantasie verbinden.',
    material: 'Nichts',
    steps: [
      'Macht die Bewegung eines Tieres vor: Hund krabbelt, Frosch hüpft.',
      'Macht den passenden Laut dazu.',
      'Lasst euer Kind mitmachen.',
      'Wechselt zwischen zwei bis drei Tieren.',
    ],
    durationMin: 8,
  },
  {
    id: 'td-einkauf-helfen',
    title: 'Beim Einkaufen helfen',
    fromWeeks: 78,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Beteiligung statt Bespaßung.',
    material: 'Nichts',
    steps: [
      'Gebt eurem Kind einen konkreten Auftrag: "Such die Bananen."',
      'Lasst es leichte Dinge in den Wagen legen.',
      'Benennt, was ihr kauft.',
      'Rechnet mit längerer Einkaufszeit.',
    ],
    durationMin: 20,
  },
  {
    id: 'td-schaufel-sand',
    title: 'Im Sand graben',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Grob- und Feinmotorik, Materialerfahrung.',
    material: 'Sandkasten, Schaufel, Eimer',
    steps: [
      'Zeigt Schaufeln, Füllen und Ausleeren.',
      'Baut selbst etwas und lasst es umwerfen.',
      'Benennt nass und trocken.',
      'Hände waschen nicht vergessen.',
    ],
    durationMin: 25,
  },
  {
    id: 'td-warten-lernen',
    title: 'Kurz warten',
    fromWeeks: 78,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Erste Impulskontrolle üben – in sehr kleinen Schritten.',
    material: 'Eine Sanduhr oder ein Timer',
    steps: [
      'Kündigt an: "Wenn der Sand durch ist, sind wir dran."',
      'Startet mit dreißig Sekunden.',
      'Bleibt daneben und lenkt ab.',
      'Steigert die Zeit erst, wenn es zuverlässig klappt.',
    ],
    durationMin: 5,
  },
  {
    id: 'td-fotos-benennen',
    title: 'Familienfotos anschauen',
    fromWeeks: 64,
    toWeeks: 156,
    area: 'sprache',
    goal: 'Personen benennen und Erinnerungen verknüpfen.',
    material: 'Ausgedruckte Fotos oder ein einfaches Album',
    steps: [
      'Zeigt ein Foto und benennt die Person.',
      'Erzählt kurz, was auf dem Bild passiert ist.',
      'Fragt: "Wer ist das?" und wartet.',
      'Nehmt Fotos, die euer Kind selbst erlebt hat.',
    ],
    durationMin: 8,
  },
  {
    id: 'td-deckel-schrauben',
    title: 'Deckel auf- und zuschrauben',
    fromWeeks: 78,
    toWeeks: 156,
    area: 'motorik',
    goal: 'Drehbewegung der Hand üben.',
    material: 'Leere Schraubgläser oder Flaschen in verschiedenen Größen',
    steps: [
      'Legt Behälter und passende Deckel getrennt hin.',
      'Zeigt einmal das Aufschrauben.',
      'Lasst euer Kind zuordnen und drehen.',
      'Nur Behälter ohne Reste, keine Glasgefäße.',
    ],
    durationMin: 12,
  },
  {
    id: 'td-spaziergang-langsam',
    title: 'Der langsame Spaziergang',
    fromWeeks: 60,
    toWeeks: 156,
    area: 'sinne',
    goal: 'Die Umgebung im Tempo des Kindes erkunden.',
    material: 'Nichts',
    steps: [
      'Nehmt euch für hundert Meter zwanzig Minuten Zeit.',
      'Bleibt stehen, wo euer Kind stehen bleibt.',
      'Benennt, was es anschaut.',
      'Lasst es Steine, Blätter und Stöcke sammeln.',
    ],
    durationMin: 20,
  },
  {
    id: 'td-becherturm-hoch',
    title: 'Höher stapeln',
    fromWeeks: 70,
    toWeeks: 156,
    area: 'kognition',
    goal: 'Ausdauer und Feinmotorik steigern.',
    material: 'Bausteine oder Becher',
    steps: [
      'Baut gemeinsam einen Turm.',
      'Zählt jeden neuen Stein laut.',
      'Lasst umwerfen, wenn es soweit ist.',
      'Versucht beim nächsten Mal, einen Stein höher zu kommen.',
    ],
    durationMin: 12,
  },
  {
    id: 'td-nein-alternative',
    title: 'Statt Nein eine Alternative',
    fromWeeks: 56,
    toWeeks: 156,
    area: 'sozial',
    goal: 'Konflikte reduzieren, ohne Grenzen aufzugeben.',
    material: 'Nichts',
    steps: [
      'Wenn etwas nicht erlaubt ist, benennt kurz, warum.',
      'Bietet sofort eine erlaubte Alternative an.',
      'Bleibt bei der Grenze, auch wenn Protest kommt.',
      'Erklärt hinterher noch einmal in Ruhe.',
    ],
    durationMin: 2,
  },
  {
    id: 'td-topf-interesse',
    title: 'Das Töpfchen kennenlernen',
    fromWeeks: 90,
    toWeeks: 156,
    area: 'alltag',
    goal: 'Ohne Druck Interesse an der Sauberkeitsentwicklung wecken.',
    material: 'Ein Töpfchen',
    steps: [
      'Stellt das Töpfchen ins Bad, ohne Aufforderung.',
      'Lasst euer Kind sich angezogen daraufsetzen.',
      'Benennt, wozu es da ist, wenn Interesse kommt.',
      'Kein Drängen, kein Zeitplan, keine Belohnung.',
    ],
    durationMin: 5,
  },
]
